### ISSUE TITLE
Bucketlist

### ISSUE THREAD

**Issue by genboy** [genboy/Festival#11]
Todo towards v1.0.4-11:
- [x] add configs option 'Msgdisplay' for persistant display area messages;
- off; no one incl. ops will see any msg as default
- op; area whitelisted ops will always see the area messages
- on; ops will always see the messages
- [x] clean up area empty event values after command  event chance 

- [x] Create [github development project](https://github.com/genboy/Festival/projects/1)

Updates and functionality will be added as time permits.
With small [donations](https://paypal.me/genboy) i'm able to invest more time building and maintaining Festival, or at least convince non-minecrafters there's a value to it.

**Comment by genboy** [comment]
[First Release v1.0.3-11](https://poggit.pmmp.io/p/Festival/1.0.3-11):
- [x] Area info popup i.o. player chat msg 
- [x] Config area messaging type (Msgtype tip||pop )
- [x] tp drop player to center area without damage
- [x] check all permissions
- [x] update infographic
- [x] ! changed the name 'barrier' to 'passage' or 'pass' (reflecting more the flag purpose)

**Comment by MateiGamingYTB** [comment]
man when i do /fe flag areaname msg off they still apear in chat
How i can do to don`t apear mesagges when enter or exit areas?

**Comment by mote166** [comment]
yea same here i set the msg flag to true (so it gets disabled) in the config and the file and in-game but the messages are still there , i even tried to put them all to false just in case but still the messages didn't disappear,  this feature is kinda useless in my opinion tbh

**Comment by genboy** [comment]
Hi, thank you for using the plugin and pointing this out. Firstly, ops will always see the area messages, players won't if msg flag is true. I will check the functionality, because i'm not sure about the whitelisted players seeing messages, and get back here if the flag really doesn't work as expected.

**Comment by genboy** [comment]
@MateiGamingYTB @mote166 
I checked with Festival [v1.0.2-11](https://poggit.pmmp.io/p/Festival/1.0.2-11) (pmmp 743); 
With the fast toggle and straightforward commands
- /fe msg AREANAME
- /fe flag AREANAME msg true 

both working as expected;
Flag goes up (on/true); Player does not see the area messages, Whitelisted players won't see messages. Messages are always visible for ops.

Please let me know if 
- it is expected not to hide the messages for whitelisted players
- there is an error or something

I'm working on the next release which will take the messages out of the chat dialogue + barrier-flag change and a config variables change. This will be released ASAP.
Hope all can cope with the coming needed adjustments. Thank you!

**Comment by mote166** [comment]
oh so only ops will see the message ? well then i have nothing else to say but try to remove it from ops too, and keep up the good work bro :+1:

**Comment by MateiGamingYTB** [comment]
Yes, thanks

**Comment by MateiGamingYTB** [comment]
@genboy Can u add in feature to plugin, in area u cant drop items? By a config means u will set false to can dropping items and true to can't

**Comment by mote166** [comment]
btw there's a plugin that disables drop for the whole server u can find it in my repo 





-------- Original message --------

**Comment by mote166** [comment]
@MateiGamingYTB  btw theres a plugin that disables drop for the whole server you can find it in my repo .

**Comment by genboy** [comment]
@MateiGamingYTB yes, good idea! 
Think you mean like in Worldguard? I currently use the Worlds plugin to control flight/drop/explode etc. worldwide and will  take a closer look at both [WorldGuard](https://github.com/Muqsit/WorldGuard/wiki/Tutorial#toggle-item-drops) and [Worlds](https://github.com/survanetwork/Worlds#usage) to prepare a nice additional and sustainable list of flags to the [project](https://github.com/genboy/Festival/projects/1) for version v1.0.5-11. 
Please have a little patients, i'll first put up v1.0.4-11 for release with a defaults fallback that will make adding options in future updates less painfull for server admins.

**Comment by mote166** [comment]
can u make it check whether the player has the permission to use the command and if he hasn't it doesn't execute the command ?

**Comment by genboy** [comment]
@mote166 yes, i think i can add this in the shape of a perm-flag; 
true = player permissions are checked for the area commands, 
false = area commands will always execute as op. 
i'll at this to my todolist

**Comment by mote166** [comment]
yes thank you .

**Comment by MateiGamingYTB** [comment]
This plugin will be very popular

**Comment by genboy** [comment]
@moto166 the perms-flag implemented in a test version works ok but side effect is that commands triggered by the area for players without permission will send a message that the command is not allowed for that player. This should be blocked silently.. 
The command can be of any kind of plugin so i'm now looking for a way to check the player permission based on the command string before the command is executed - or i'll find a way to temporary turn of the command 'no permission' message when the area event triggers the commands. 
If you know an example or plugin that might use comparable functionality, pls let me know.

**Comment by mote166** [comment]
ok thank you , ill start using it once the new release is done and published so i can use its full awesome functions , but i suggest flipping the flags (false/true) to match the idea that is already in our mind and make it easier for the players to set the flags ,

like if u want a flag to work then set it to true and if u wanna disable it set it to false , for ex:

if u don't want the players to edit the area set the edit flag to true so the area gets protected from block break/place .

this is the most used way and the most sense making way of setting up the flags .

**Comment by genboy** [comment]
@mote166  nice to know what you (like to) experience using the flags. I'll give the god flag swappin another thought and decide soon. Thank you for your feedback!

**Comment by genboy** [comment]
@mote166 @MateiGamingYTB

[v1.0.4-11 is here](https://github.com/genboy/Festival/releases/tag/v1.0.4-11), poggit release will take a bit longer, i learned a lot thanks!

All flags stay the same +

[x] drop flag = true: can't drop stuff here 

[x] perms flag = true: use player permission rules for commands

Perms are not my speciality, let me know if something is not ok

Have fun!

**Comment by MateiGamingYTB** [comment]
Cool

**Comment by genboy** [comment]
@SOF3 @mote166 @robske110 @MateiGamingYTB @SaigatamaAiNA @SivannOnline @NeonBlueSoul @urParadox @CraftyDex @louise76 @SOF3 @mote166 @robske110 and other earlybirds

i hope you'll enjoy [Festival v1.0.4-11](https://poggit.pmmp.io/p/Festival/1.0.4-11) and maybe find the time & words to review it.

For development also see [this note](https://github.com/genboy/Festival/pull/21)

#### Thank you for your attention towards the Festival plugin

This issue wil close now

**Comment by SOF3** [comment]
Don't mention me just because you have an update... I don't even use the plugin.
