### ISSUE TITLE
Festival 2 the remake - What takes me so long?

### ISSUE THREAD

**Issue by genboy** [genboy/Festival#117]
Well Festival 2 is Festival rewritten completely for monkey users like myself :) - here's a short preview
https://genboy.net/sneak-preview-festival-2-test/

![pmmp_festival2_uitest](https://user-images.githubusercontent.com/30810841/51426890-023aff80-1bf1-11e9-98d9-974958383dea.PNG)

![pmmp_festival2_uitest_2](https://user-images.githubusercontent.com/30810841/51426947-ad4bb900-1bf1-11e9-80bd-f6f861a6e799.PNG)

![pmmp_festival2_uitest_2b](https://user-images.githubusercontent.com/30810841/51426975-f00d9100-1bf1-11e9-92bf-fb3ddfd4cabc.PNG)

![pmmp_festival2_uitest_4](https://user-images.githubusercontent.com/30810841/51426949-b2a90380-1bf1-11e9-9e22-0b1d94ab5507.PNG)

![pmmp_festival2_uitest_4b](https://user-images.githubusercontent.com/30810841/51426950-b50b5d80-1bf1-11e9-94e8-57182bf77185.PNG)

![pmmp_festival2_uitest_5](https://user-images.githubusercontent.com/30810841/51426952-b6d52100-1bf1-11e9-9fdf-fca41fe53694.PNG)

![pmmp_festival2_uitest_6](https://user-images.githubusercontent.com/30810841/51426953-b9377b00-1bf1-11e9-83da-b83e18026844.PNG)

![pmmp_festival2_uitest_3](https://user-images.githubusercontent.com/30810841/51426948-b0df4000-1bf1-11e9-8283-83641209076e.PNG)

**Comment by Flucid** [comment]
Looks great! Nice work.

**Comment by genboy** [comment]
Untill now i've been testing 
  - (re)installation with area's & config translated automatically from old festival sources
  - formsUI in combination with cube area's and new sphere shape area type.

My latest newsetup repo has all area's, configs and level flags controlled by clicking and typing in the UI panels (events and flags, except barrier, not implemented yet due to testing along side Festival 1.0.8). 

All control ingredients are here but the usabillity can be much better. It needs some time to restructure. 
![minecraft 27-1-2019 16_49_41](https://user-images.githubusercontent.com/30810841/51803358-837b3d80-2254-11e9-861e-62f46aff257e.png)
![minecraft 27-1-2019 16_50_24](https://user-images.githubusercontent.com/30810841/51803360-8bd37880-2254-11e9-8ee3-0ef71126f9e4.png)
![minecraft 27-1-2019 16_50_35](https://user-images.githubusercontent.com/30810841/51803361-8e35d280-2254-11e9-9c79-aba8b1a9afaa.png)
![minecraft 27-1-2019 16_51_08](https://user-images.githubusercontent.com/30810841/51803362-90982c80-2254-11e9-8deb-084e13db254e.png)

Now working on (actually rewriting everything including:)
- player session including area info and a manager for edit modes
- better UI setup with less clicks (and testing options for shortkeys/item holds)
- structure for area options and flags

Hope i can find time to speed up development, see for more info the [project page](https://github.com/genboy/Festival/projects/2)
Cheers

**Comment by genboy** [comment]
Almost ready for a dev-release including 
- UI for level flags
- creating sphere area's with radius OR Diameter :)
- translations

**Comment by genboy** [comment]
Ready to move on
