### ISSUE TITLE
Fly for CMode

### ISSUE THREAD

**Issue by Bruth78** [genboy/Festival#125]
Hi.
So basically everyone with gmc can’t fly. (without op)
At first every Guest was able to fly so I turned flight in every Area to NoFly. (I set everything I saw in the Plugin-Data to NoFly)
But how do i let ppl without op and with gmc fly?
I also gave them the Mod rank with the permission festival.access, Hope you’ll read this soon, thanks for your help!

**Comment by genboy** [comment]
Hi @Bruth78,  i hope i understand your question;
Depending on how gmc is assigned to those players (manual select or automatically)
If players should not fly outside area's (incl. gmc players), the fly flag should be on for that world. (in config.yml) . If certain players should fly in an area where others can not, maybe you can use the area whitelist?

**Comment by Bruth78** [comment]
Yeah, but what do I do so only Staff with gmc can fly outside of areas like at Factions world or wherever.
Also thanks for replying that quick, @genboy

**Comment by genboy** [comment]
Hi @Bruth78, you are welcome.
festival.access permission should do the trick but i also think Festival should allow any player with gmc to fly, do that what i'll add in a new dev version tonight. Will post here when ready for testing.

**Comment by genboy** [comment]
Hi @Bruth78  
Here is the update [dev version 63](https://poggit.pmmp.io/ci/genboy/Festival/Festival) |  [dwnld phar](https://poggit.pmmp.io/r/53288/Festival_dev-63.phar)
Now with default flying allowed for gmc players (besides players/ops with 'festival' or 'festival.acces')
Hope you can now accomplish what you like.

**Comment by Bruth78** [comment]
@genboy
Thanks!
It seems to be fixed

**Comment by genboy** [comment]
Good to hear it works @Bruth78
To make sure it is fixed i hope you can let me know; can your gmc players without 'festival' or 'festival.acces' or other op permissions, still fly now?
Thank you, enjoy!

**Comment by Bruth78** [comment]
Yes works even without the festival.access perm or the festival perm.
Thank you for responding that quick and sorry that I didn’t respond, I didn’t see your message

**Comment by genboy** [comment]
Thank u very much for your feedback! @Bruth78
