### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Bruth78** [genboy/Festival#127]
Heya, sorry that I created a ticket, AGAIN.
Im kinda stupid I gotta admit XD.
So I’m currently experiencing problems with Perms.
So I gave the Mod rank the permission to use gamemode so I added the Pocketmine.command.gamemode perm to the Mod rank and restarted the server.
But it doesn’t work, lately I saw the option called “Perms” in the config of Festival so might the issue come from that?
( I disabled Perms )
Thank you ;)

**Comment by CryptoKey98** [comment]
PurePerms is case sensitive. Make sure you have no upper-case letters.

**Comment by Bruth78** [comment]
Yeah I did.
Hmm, sorry realized I used a captible letter

**Comment by genboy** [comment]
Thank you @CryptoKey98  for helping out

**Comment by Bruth78** [comment]
But it still doesn’t work tho

**Comment by genboy** [comment]
@Bruth78 hope you can fix it knowing;
If the perms flag is false (default) all area event commands are executed with OP permissions, providing the option to use any command in combination with players and area's. (see [wiki - common-issues](https://github.com/genboy/Festival/wiki/4.-Common-issues) )

**Comment by Bruth78** [comment]
@genboy is it possible that your plugin bans lava?

**Comment by genboy** [comment]
@Bruth78 do you mean separate from the fire flag?  it does with the fire flag. i'll review [the function](https://github.com/genboy/Festival/blob/435201aa9f7a0e902ad4aa5a686aa4742e222713/src/genboy/Festival/Main.php#L1469)

**Comment by genboy** [comment]
@Bruth78 do you mean separate from the fire flag?  it does with the fire flag. i'll review [the function](https://github.com/genboy/Festival/blob/435201aa9f7a0e902ad4aa5a686aa4742e222713/src/genboy/Festival/Main.php#L1469)
