### ISSUE TITLE
Griefing Area from outside

### ISSUE THREAD

**Issue by dearminder** [genboy/Festival#132]
I have made a basic area flags but they can be abused from outside of area (like on gif) it works for all types of flags (tnt, pvp etc.)
https://gfycat.com/energeticdemandinggoldenmantledgroundsquirrel

**Comment by genboy** [comment]
@dearminder  Thank you very much for reporting this, very sorry for the inconveniences. I've come up with a solution for this and will try to implement it soon.

**Comment by genboy** [comment]
Hi @dearminder 
Festival code is adjusted in some functions to determine the needed position to validate the action(flag).
Here's the [dev phar](https://poggit.pmmp.io/r/54070/Festival_dev-67.phar) at [poggit ](https://poggit.pmmp.io/ci/genboy/Festival/Festival) for testing.

**Comment by Karanztez** [comment]
Thx

**Comment by dearminder** [comment]
Just checked and its working :) Also u forgot to clean areas.json and config.json in this commit ;)

**Comment by genboy** [comment]
@dearminder Thanks for testing & reporting, here's the clean areas and config [dev update](https://poggit.pmmp.io/ci/genboy/Festival/Festival)
Cheers
