### ISSUE TITLE
Perms Flag

### ISSUE THREAD

**Issue by Bruth78** [genboy/Festival#146]
I know ive opened this ticket a while ago but im experiencing the same problem and i forgot how we fixed it at the first place.
So basically pureperms don't seem to work for me
To what should i change the flag to?

**Comment by genboy** [comment]
Hi @Bruth78, maybe you mean [this issue](https://github.com/genboy/Festival/issues/127) about case sensitiveness or the fix i did for [gmc](https://github.com/genboy/Festival/issues/125) ?
Perms flag true should bind the area event commands to the player perms, hope you can make it work the way you like.

**Comment by Bruth78** [comment]
Thanks for everything.
Just had to turn everything to true in order to enable perms
