### ISSUE TITLE
Translated to Spanish

### ISSUE THREAD

**Issue by bptube** [genboy/Festival#147]
I translated the latest Spanish version, please tell me if I miss something. https://github.com/bptube/Festival-en-espa-ol

**Comment by genboy** [comment]
Muchas gracias @bptube, it's in [dev update](https://poggit.pmmp.io/ci/genboy/Festival/Festival) now for testing

**Comment by genboy** [comment]
Test with .phar did not work out, trying to fix it now

**Comment by bptube** [comment]
It is the language system that does not work "/ fe lang nl" also gives error

**Comment by bptube** [comment]
https://ibb.co/s5RQvn1

**Comment by genboy** [comment]
@bptube  ill try to fix the language translation with https://www.php.net/html-entity-decode

**Comment by bptube** [comment]
There is a problem with your language management system, I downloaded the original version without modifying it and even then I could not change the language.
Demonstrative video: (Note that it is the original version, not edited at all)
https://www.youtube.com/watch?v=kIS2k-fpNcE

**Comment by genboy** [comment]
Yes i've noticed it 2, i'll will take new code from a good plugin and add that in Festival.

**Comment by bptube** [comment]
It works, it works, it work...
I made it work, although for that the en.json file was replaced, besides I can not find some texts that are still in English.
Edited files: en.json -> translated
Main.php -> now decodes utf-8
Demo:
https://ibb.co/fnbY3tK
https://ibb.co/5K5f6k9
https://ibb.co/1Lv9vjn
https://ibb.co/998YtsP

**Comment by genboy** [comment]
@bptube Great to hear that! I've done a check myself (did read here earlier, sorry for the late reply) and anupdate in the [languages branch](https://github.com/genboy/Festival/tree/Translations) with working language swith. Now we need to fix the correct utf character handling. I'll hope to find some time to find the best way of using most types of languages (will take a look at texter for example). Cheers

**Comment by genboy** [comment]
Hi @bptube, [new dev update](https://poggit.pmmp.io/ci/genboy/Festival/Festival) includes the correct characters (json utf-8 encoding fixed) - Thank you & enjoy!

**Comment by genboy** [comment]
:) @bptube, @dearminder, i learned a bit how to make the best of the tranlations - the original Polish and Spanish texts look better now. Cheers
![Minecraft 23-4-2019 22_21_37](https://user-images.githubusercontent.com/30810841/56613829-c6f90400-6617-11e9-8707-f4855ce0bc65.png)
![Minecraft 23-4-2019 22_34_22](https://user-images.githubusercontent.com/30810841/56613905-f6a80c00-6617-11e9-87b2-930bb4107bea.png)
