### ISSUE TITLE
Join/Leave messages

### ISSUE THREAD

**Issue by Tumeden** [genboy/Festival#15]
Join/leave messages wont disable by command.

Also, there's absolutely no way to disable "enter the center of area shop" messages, and its super annoying.

**Comment by genboy** [comment]
@Tumeden yes, it is annoying indeed;
There are [more options](https://github.com/genboy/Festival/issues/11) for next version in [progress](https://github.com/genboy/Festival/tree/dev-ext).(with the op-message-display default off). Also please read [v1.0.3-11](https://github.com/genboy/Festival/releases) about the changes. I hope for now you can experience the creative possibillities Festival brings and will be more satisfied with v1.0.4-11, thank you!
