### ISSUE TITLE
Polish Translation fix

### ISSUE THREAD

**Issue by dearminder** [genboy/Festival#156]
I dont know how to use pull so i did it like this
https://pastebin.com/wX2hfvZA

ps: Its pl not po ;)

**Comment by genboy** [comment]
Will change the file and language code to pl, dziękuję bardzo @dearminder!

**Comment by genboy** [comment]
Hi first i had some trouble adding the file, now it works - [dev update](https://poggit.pmmp.io/ci/genboy/Festival/Festival), @dearminder Twoje zdrowie!
