### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Snickerzzz** [genboy/Festival#175]
I created protected areas for my spawn, pvp arena, etc and when I deopped myself and tested to see if the areas were safe, it didn't work. I was able to break the blocks.

There is also a problem with the flight flag. I wanted it disabled in certain regions, but instead it disables it everywhere. 

Thank you!

**Comment by genboy** [comment]
Hi @Snickerzzz, it might be your (op)player is whitelisted in the area's?
Auto whitelisting can be turned off in config.yml

Flight flag can be troublesome. 
Make sure config.yml sets level defaults flight flag off (false = flight allowed), then area's should have flight flag off/false on creation. The server should allow flight, the world should allow flight, then when an area has flight flag on only there it should disallow flight. Please also [read wiki](https://github.com/genboy/Festival/wiki/4.-FAQ-&-Common-issues). 

After reading and trying please let me know if it's still a problem, hope you can enjoy Festival!

**Comment by genboy** [comment]
@Snickerzzz, are these above still buggin you?
