### ISSUE TITLE
Crash!!!!!!!!! 

### ISSUE THREAD

**Issue by GabrielYudenich** [genboy/Festival#176]
Log: 
https://mclo.gs/K5pbKgI
Please fix it!

**Comment by genboy** [comment]
Thanks for reporting @GabrielYudenich, sorry to see it crashing.
Could it be something with a command on area enter?

**Comment by GabrielYudenich** [comment]
No

Its a plugin problem.

The commands are ok.

**Comment by genboy** [comment]
Hi @GabrielYudenich, i'm looking into this.
I can see a problem caused on line 2640, command #2 is missing.
Could you send me the areas.json file? I'll check the json format Festival produced.
Thanks

Or maybe you're up to [test another dev](https://poggit.pmmp.io/ci/genboy/Festival/Festival) 1.1.4-dev or the latest dev 2.0.0-dev?

**Comment by GabrielYudenich** [comment]
I will test again

Thanks for the help
