### ISSUE TITLE
Area Overlapping

### ISSUE THREAD

**Issue by RoutinePrince15** [genboy/Festival#193]
I dont know if this is a feature that isn't added or not, but area overlapping for me doesn't work. I trying to set up a prison server and I want to protect the outer mine but let players mine the area in the middle and it just doesn't work. It won't let players mine the middle area that's inside the outer area to protect the rest of the builds. Plz help.

**Comment by genboy** [comment]
Hi @RoutinePrince15, thank you for reporting. 
What version do you use? 
In the next release (and latest dev versions) there's a new priority setting for area's to solve this overlapping-problem. Latest dev https://poggit.pmmp.io/ci/genboy/Festival/Festival/dev:94 is still being tested.

In older Festival versions it might help to create the inner-overrulling area last. (or move the area code in areas.json down in the array order)

Let me know if it still does not work, thank you
