### ISSUE TITLE
Are forms completed?

### ISSUE THREAD

**Issue by dearminder** [genboy/Festival#194]
I just wanted to try make sphere area with form and i cant select block for center of area (I get message to choose it but i cant do it, no response for clicking any block)

**Comment by genboy** [comment]
Hi @dearminder, that's bad, i think i left something out of the manuals sorry. If the forms are used for area creation you have to use the magic item, 201 purpur block. ( the old way with commands should still work, extended with rad(ius and dia(meter) in second command, but can't be mixed with the forms area creation). Let me know if this was the problem.
Thank you for checking out the new version!

**Comment by dearminder** [comment]
Oh yea it works, Also quick question? Did you changed saving of configs because I think old sphere just dissapeared from my server

**Comment by genboy** [comment]
@dearminder area's are saved in the areas.json, levels in levels.json file, the configs have nothing to do with that. Maybe you mean something else?

**Comment by dearminder** [comment]
19:56:13] [Server thread/INFO]: [Festival] Previous config.yml used for configuration!

[19:56:13] [Server thread/INFO]: [Festival] Level data set loaded!

[19:56:13] [Server thread/INFO]: [Festival] 14 flags and 0 commands in 1 areas (7 levels)

While in old config I have 2 areas

**Comment by genboy** [comment]
Hi @dearminder, do you have a backup of your old areas.json? remove the current areas.json and put that old areas.json in the main Festival folder (not the resource folder) and restart.

The settings in the config.yml are for world/level defaults; in the new version they are used once to setup the levels.json and config.json files. The old areas.json file is used and rewritten with the future changes. Hope that helps, let me know.

**Comment by dearminder** [comment]
I dont fully understand I deleted all from plugin_data (festival folder) and pasted backup of old saved area and config but one sphere keep dissapearing, one area is created and rest of them lands in levels , Can we Move it To Some DMs To not spam here?

**Comment by genboy** [comment]
Maybe you can email me the areas.json file to have a look?

**Comment by genboy** [comment]
Hi @dearminder your areas.json looks fine. Could it be the level of your sphere-area has changed name or is not loaded at all in the server? Then the area will not load either.

When looking at your areas.json first i had to adjust the area level names otherwise the areas will not load. With the level names adjusted to loaded levels both areas are loaded.

![Screenshot_2019-07-15 Server pro Professional Game Server Hosting](https://user-images.githubusercontent.com/30810841/61199410-25e18d00-a6de-11e9-8d33-5bdcb0db9e50.png)

Hope this is solves the problem, otherwise let me know

**Comment by dearminder** [comment]
So i managed to relook on both settinngs new and old
1. Old config file not works, ui is crashing by then (had to manualy configure new config looking on old settings,
2. Spheres are changed because creating new sphere and applying positions from old files make it not match sphere i built with diffrent plugin (before it was matching perfectly)

**Comment by genboy** [comment]
Hi @dearminder, thank you for elaborating these issues. I'm not sure and like to find out what exactly happened. For a start, could you try to follow these steps? If something goes wrong we can compare the outcome.

- 1 make sure the config.yml and areas.json files are save (yep you send them) 
- 2 upload the latest Festival dev .phar ([now #95](https://poggit.pmmp.io/ci/genboy/Festival/~)) to plugins folder
- 3 restart server and look in plugins/Festival folder

![Screenshot_2019-07-15 Server pro Professional Game Server Hosting(1)](https://user-images.githubusercontent.com/30810841/61228699-13d80c80-a727-11e9-8acf-593624c6d938.png)

- 4 Then remove all new files and place back the config.yml and areas.json previous used

![Screenshot_2019-07-15 Server pro Professional Game Server Hosting(2)](https://user-images.githubusercontent.com/30810841/61228903-6d403b80-a727-11e9-81d1-2d599fc854ca.png)

- 5 restart server and check the console

![Screenshot_2019-07-15 Server pro Professional Game Server Hosting(4)](https://user-images.githubusercontent.com/30810841/61229157-f0619180-a727-11e9-91b9-96798a82e73d.png)

I've tested with your files, with only the levelnames in the areas.json file changed to levels my server has available for testing.

**Comment by dearminder** [comment]
Still spheres dont match blocks as it was before but its only my problem ;) Thanks
