### ISSUE TITLE
Error when creating area

### ISSUE THREAD

**Issue by benda95280** [genboy/Festival#198]
Hello,

I'm working on the v94.
I've try to setup an area, but when creating, i was thinking cancel my area.
I don't know where i've clicked, but it crashed:
[21:47:17] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "plugins/Festival_dev-94.phar/src/genboy/Festival/FormUI" at line 764

I was no more able to have the Menu again, it was showing:
**You'r already selecting a position!**

**Comment by benda95280** [comment]
I've found how to reproduce:
- Close the form when you add a name to your area

**Comment by genboy** [comment]
Hi @benda95280, that is serious trouble, i will look at this next couple of days to fix this error.
Thank you again!

**Comment by genboy** [comment]
Hi, i tested and fixed many issues + extended some options. 
Please keep your original areas.json (from befor v2 ) for installing, first do a clean install with  phar file. After the first restart add the old areas.json in the Festival folder and edit the (new) config.yml in /resources, then restart for full install.

https://poggit.pmmp.io/ci/genboy/Festival/Festival
