### ISSUE TITLE
Level Flags (from Flag "msg" seems reversed)

### ISSUE THREAD

**Issue by benda95280** [genboy/Festival#200]
Hello,

I'm working with the version 94.

It seems the flag "msg" is reversed.
If flag set to false, it show messages.

- Expected: true to show message.
- Why: If we put all flags to false, we have messages. But i expect if i set all to false, to have everything disabled.

Regards.

**Comment by genboy** [comment]
Hi @benda95280, i know, it is a bit strange. 
In the start of development i could not find 1 basic rule for 'flags' usage methods. Their are many methods but most of them are not really flags but switches. Flags are about signaling, not turning something on or off.  
So i made one rule from the Festival perspective; 

**Any flag true will protect the area and the players in it.**
edit: true (on) means no breaking/building by players.
shoot: true (on) means no shooting by players.
msg: true (on) means no messages (protecting the area)

If msg true would mean you can see messages, then what about the edit flag? edit: true means the player can edit? 
With 'Any flag true will protect the area and the players in it' the real purpose of the flag usage becomes clear.
Please let me know if you find any inconsistencies in this (by setting the flags).
Cheers!

**Comment by benda95280** [comment]
Hmm, i've found another problem with the usage of the V2.

Could it be possible to **disable whole new functionnality for level management** ?
Like:
_"options":{"lang":"en","itemid":201,**"levelmanagement":"false"**,"msgdisplay":"op","msgposition":"msg","areatitledisplay":"op","autowhitelist":"on","flightcontrol":"on"}_

Because it's overriding all of my world, and i've to set parameters in my plugin, and in your.
(Some world are for games, others for Adventure, ...)

Set everything on false, do not help me 😭, because no more PVP on my PVP/games worlds.

**Comment by benda95280** [comment]
> Hi @benda95280, i know, it is a bit strange.
> In the start of development i could not find 1 basic rule for 'flags' usage methods. Their are many methods but most of them are not really flags but switches. Flags are about signaling, not turning something on or off.
> So i made one rule from the Festival perspective;
> 
> **Any flag true will protect the area and the players in it.**
> edit: true (on) means no breaking/building by players.
> shoot: true (on) means no shooting by players.
> msg: true (on) means no messages (protecting the area)
> 
> If msg true would mean you can see messages, then what about the edit flag? edit: true means the player can edit?
> With 'Any flag true will protect the area and the players in it' the real purpose of the flag usage becomes clear.
> Please let me know if you find any inconsistencies in this (by setting the flags).
> Cheers!

It's clear 👍

**Comment by genboy** [comment]
Hi @benda95280 off by default; the option per level to turn on/off the level flag control.
Testing with the latest [dev version](https://poggit.pmmp.io/ci/genboy/Festival/)
Cheers
![Minecraft 14-7-2019 23_07_43](https://user-images.githubusercontent.com/30810841/61189367-b8594080-a68c-11e9-9c42-2a26cb7cb66a.png)
