### ISSUE TITLE
Slappers despawn when Animals and Mobs aren't allowed to spawn

### ISSUE THREAD

**Issue by AL3XPI** [genboy/Festival#209]
When I have Animals and Mobs set to not spawn and reload the server, it removes all my slappers. This is really annoying as I do not want animals and mobs to spawn at spawn, and for players to have to see them when they enter the server. Pocketmine 3.9.2 Bedrock 1.12.0 Festival 1.1.3

**Comment by genboy** [comment]
Hi @AL3XPI, thank you for sharing. Indeed annoying and should be solved. No improvement on that in [festival 2 latest edition](https://poggit.pmmp.io/ci/genboy/Festival/Festival) either. To solve this any slapper entities should be permitted.
Do you use a slapper plugin, wich one? 
For a start I'll look up how to scan for slappers and see how to implement it. 
Thank you

**Comment by AL3XPI** [comment]
I used this https://poggit.pmmp.io/p/Slapper/1.5.0

**Comment by genboy** [comment]
Thank you, i'm working on it and will let you know when test version is available. cheers

**Comment by genboy** [comment]
A small update testing with a stone circle - a sphere area with animals and mobs flag on - with 2 spawners for sheep and zombies and 2 slappers in the center. The picture shows zombies spawned outside the area and the 2 slappers still standing after server restart.
![Minecraft 28-7-2019 13_53_41](https://user-images.githubusercontent.com/30810841/62006327-87bedf80-b13f-11e9-8ab5-6db8002ac165.png)

**Comment by AL3XPI** [comment]
Nice.

**Comment by AL3XPI** [comment]
@genboy I made it so animals and mobs don't spawn at spawn with Festival 2 pocketmine 3.9.3 slapper 1.5.0 and it deleted all my slappers! Please reopen this issue or I can make another.
