### ISSUE TITLE
Error creating form.

### ISSUE THREAD

**Issue by AL3XPI** [genboy/Festival#210]
Pocketmine 3.9.3
Festival 2.
I /give 201 myself (purpur block used to create an area). I then did /fe menu, chose create new area, placed the blocks where I wanted the area to be (cube diagonal). When the area was created, I decided to add some flags, but lo and behold when I clicked area flags, it gave me this error:
![image](https://user-images.githubusercontent.com/35903333/62134705-00907980-b2af-11e9-8982-7042eff8355c.png)
Please help me fix this.

**Comment by genboy** [comment]
Hi @AL3XPI , thank you for sharing, i'll try to find out what is wrong soon. 
Does this happen with all area's, or only new area's?
After the error occures can you still play and use the menu for other functions?
If i need more info i'll let you know here, thank you

**Comment by AL3XPI** [comment]
All areas, and i can still play and the menu works.

**Comment by AL3XPI** [comment]
@genboy

**Comment by genboy** [comment]
@AL3XPI  a first test with clean setup and pmmp 3.9.3 does not show an error when creating and managing an area. More info needed, just to check, did you do a clean install first and then replace area/config files and restart? 
If you are able to check the server console, does it show the error? send it to me, thank you

**Comment by AL3XPI** [comment]
I forgot I needed to delete my old area and config files and restart the server. That will probably fix it. Doing that right now.

**Comment by AL3XPI** [comment]
@genboy

**Comment by AL3XPI** [comment]
I replaced the old phar with the new phar, and I did not delete my old files.

**Comment by AL3XPI** [comment]
I did a clean install and fixed everything. It works.
