### ISSUE TITLE
Slappers despawn when Animals and Mobs aren't allowed to spawn STILL

### ISSUE THREAD

**Issue by AL3XPI** [genboy/Festival#214]
In my previous issue @genboy you closed it. It's still not fixed however. I am using Festival 2, Pocketmine 3.9.3, and Slapper 1.5.0. I chose to not have animals and mobs spawn on my server, however after I reloaded, I was greeted with ALL OF MY SLAPPERS DELETED. I thought the issue was fixed as you closed it. Please fix this @genboy.

**Comment by genboy** [comment]
Hi, @AL3XPI the fix is still progress, sorry the issue closed automatically when I pulled the latest changes to the master repo. I'll pull this one to the dev repo too so you can download the latest development .phar at https://poggit.pmmp.io/ci/genboy/Festival/Festival

**Comment by AL3XPI** [comment]
Ok thanks.

**Comment by AL3XPI** [comment]
I tried the latest dev build and replaced the .phar file. I still cannot spawn a slapper in an area with no animals and mobs.

**Comment by AL3XPI** [comment]
@genboy

**Comment by genboy** [comment]
Hi @AL3XPI, sorry to hear that, i'll check why it's not working, let you know soon

**Comment by genboy** [comment]
Hi @AL3XPI, i'm testing with PocketMine-MP version 3.9.3 + Slapper v1.5.0 and Festival_dev-99.phar, further more PureEntitiesX v0.6.2, EssentialsPE v2.1.0, RedstoneCircuit v2.0.0 and BlockSniper v3.2.3 installed.

Placing slappers in an area with mobs and animals flags on was working allright, also logout and in, server restart and testing in other level. Still playing with the slappers.
I'm curious what's the problem so please give me al info you got. Are there error messages from festival or slapper by chance?

Somehow a first test with latest PureEntitiesX v0.6.3 no entities where moving, so i switched back to v0.6.2 for testing with slappers and working entities. 

Could you check it's Festival_dev-99.phar from poggit, restart and retry making a new area, set priority to high (1 if you haven't set any), turn on the mobs and animals flag and place basic ie. zombie and horse slappers?
And maybe check normal entities (PureEntitiesX version) do work as they should.
Thank you

**Comment by AL3XPI** [comment]
@genboy I restarted the server and it worked. Slappers function. Only if I spawn a horse or zombie the slapper spawns. If i do /slapper spawn human test, it does not work and slapper says the entity was spawned but it was automatically removed by festival. No error messages from Festival or slapper. I made a new area, disabled animals and mobs, and tried to spawn a human but it did not work. It is Festival_dev-99.phar. Priority is one. Horses and zombie slappers are able to spawn. I restarted the server many times, to no avail.

**Comment by genboy** [comment]
@AL3XPI  thank you for testing and complete feedback so i can reproduce this. I will try to find a fix in next couple of days and post here again.

**Comment by genboy** [comment]
Hi @AL3XPI, i fixed the code to keep the Slapper human. Update available for testing at [poggit](https://poggit.pmmp.io/ci/genboy/Festival/Festival)

![FlagTestSlapperHumanRemain](https://user-images.githubusercontent.com/30810841/62428780-ea971480-b705-11e9-84a1-9bf5f3336769.gif)

**Comment by AL3XPI** [comment]
@genboy it works. Thank you so much, you have been very helpful throughout this issue. This plugin is one of the best I have seen and the support for issues have been amazing. Keep being awesome.
