### ISSUE TITLE
Colored Area Titles

### ISSUE THREAD

**Issue by BootheBoys** [genboy/Festival#216]
I changed my title from "Nether Island 1" to "§l§e> §cNether Island 1§e <§r§e" and it seemed to have duplicated the area under a different name, and now I cannot seem to delete the area using the menu item. I tried using /fe del <name> but that doesn't seem to think there is an area either.

**Comment by BootheBoys** [comment]
Note: It seems to have fixed itself on the restart of the server.

**Comment by genboy** [comment]
Hi @BootheBoys, watch out because i think it is not 'fixed' but the name of the area just could not be loaded on restart. Good to know you would prefere to color the names, but maybe then it is better to us the texter-plugin sorry
