### ISSUE TITLE
Fly bug

### ISSUE THREAD

**Issue by StringerJ** [genboy/Festival#217]
Whenever i enable fly it lets people fly wherever past the protected area and when i reload my server the config just reset.

**Comment by genboy** [comment]
Hi @StringerJ, hope to help you out. 
First, unless the config flightcontrol options is on, flight should not be regulated by Festival. 
Just to check;
Did you remove the old config.yml file used for installation befor restart?
Do you mean you've set the config flightcontrol option and it changed after reload?
![Manage configuration](https://genboy.net/wp-content/uploads/2019/06/manager_configuration.png)

There's also the level flight flag, do you use that?
![Manage Level use option and flags](https://genboy.net/wp-content/uploads/2019/07/manage_level_option.jpg)

Hope we can solve this, let me know

**Comment by StringerJ** [comment]
i figured out the flight problem but when i  /reload my config gets deleted and lose all areas. This is so annoying
