### ISSUE TITLE
Priority Tutorial

### ISSUE THREAD

**Issue by dearminder** [genboy/Festival#218]
Can you make some tutorial in wiki how priority works because i tried it with 2 overlaping areas and didnt get it to works properly

**Comment by genboy** [comment]
Hi @dearminder, good you mention this info is missing. he priority is still a bit experimental.

Set priority
  The higher number has priority, levels are always lowest priority 0.
  /fe pri(prior/priority) <AREANAME> set <number int>

I added some wiki info but will keep testing it to make sure not to misinform you. Let me know if it works for you.

**Comment by dearminder** [comment]
I just noticed that one of my Areas stuck on priority 2, i wasnt able to change it via gui, changed it via command to 0 and 

> ErrorException: "Undefined offset: 1" (EXCEPTION) in "plugins/Festival-master/src/genboy/Festival/Festival" at line 551
> 
> 13:25:30 <Server thread/Debug> #0 plugins/Festival-master/src/genboy/Festival/Festival(551): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[19] Undefined offset: 1, string[72] /home/minecraft/plugins/Festival-master/src/genboy/Festival/Festival.php, integer 551, array[10])
> 
> 13:25:30 <Server thread/Debug> #1 src/pocketmine/command/PluginCommand(58): genboy\Festival\Festival->onCommand(object JackMD\NameSpaceRemover\CustomPlayer, object pocketmine\command\PluginCommand, string[2] fe, array[3])
> 
> 13:25:30 <Server thread/Debug> #2 src/pocketmine/command/SimpleCommandMap(295): pocketmine\command\PluginCommand->execute(object JackMD\NameSpaceRemover\CustomPlayer, string[2] fe, array[4])
> 
> 13:25:30 <Server thread/Debug> #3 src/pocketmine/Server(2142): pocketmine\command\SimpleCommandMap->dispatch(object JackMD\NameSpaceRemover\CustomPlayer, string[19] fe pri Strefa 0 set)
> 
> 13:25:30 <Server thread/Debug> #4 src/pocketmine/Player(3298): pocketmine\Server->dispatchCommand(object JackMD\NameSpaceRemover\CustomPlayer, string[19] fe pri Strefa 0 set)
> 
> 13:25:30 <Server thread/Debug> #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(278): pocketmine\Player->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
> 
> 13:25:30 <Server thread/Debug> #6 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
> 
> 13:25:30 <Server thread/Debug> #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(117): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
> 
> 13:25:30 <Server thread/Debug> #8 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
> 
> 13:25:30 <Server thread/Debug> #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(117): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
> 
> 13:25:30 <Server thread/Debug> #10 src/pocketmine/Player(3379): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
> 
> 13:25:30 <Server thread/Debug> #11 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
> 
> 13:25:30 <Server thread/Debug> #12 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[18] 89.66.23.232 62331, object raklib\protocol\EncapsulatedPacket, integer 0)
> 
> 13:25:30 <Server thread/Debug> #13 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
> 
> 13:25:30 <Server thread/Debug> #14 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
> 
> 13:25:30 <Server thread/Debug> #15 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
> 
> 13:25:30 <Server thread/Debug> #16 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
> 
> 13:25:30 <Server thread/Debug> #17 src/pocketmine/Server(2456): pocketmine\snooze\SleeperHandler->sleepUntil(double 1564658730.6585)
> 
> 13:25:30 <Server thread/Debug> #18 src/pocketmine/Server(2316): pocketmine\Server->tickProcessor()
> 
> 13:25:30 <Server thread/Debug> #19 src/pocketmine/Server(1889): pocketmine\Server->start()
> 
> 13:25:30 <Server thread/Debug> #20 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
> 
> 13:25:30 <Server thread/Debug> #21 (1): require_once(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)
> 
> 13:25:30 <Server thread/Info> dearminder left the game
> 
> 13:25:30 <Server thread/Info> dearminder[/_poop_] logged out due to Internal server error
> 
> 13:25:30 <RakLibServer thread/Notice> Blocked _poop_ for 5 seconds

**Comment by genboy** [comment]
Hi, i'm looking into this. I noticed my prev. comment showed an incomplete command string, sorry for that, it should be:
 /fe pri 'AREANAME' set 'number int'
Maybe that works? I'll have to check what causes the gui not to change the priority.

**Comment by dearminder** [comment]
Ok this command works, but priority still doesnt seem to works, My settings:
For level  mobs and animals flags disabled
for a area they are enabled and inside this, another area where these flags are disabled

**Comment by genboy** [comment]
Allright, thank you for elaborating your ingame situation, i'll test and check with animals and mobs flag behaviors in priority area's.

**Comment by genboy** [comment]
Hi @dearminder, i can not reproduce this misfunction o f priority settings yet.
I've tested with pureEntitiesx, some spawners for sheep (animals) and creepers (mobs), an area with priority 3 and both animals and mobs flag on, all inside an area with priority 1 and both animals and mobs flag off. The behavior was correct, no direct spawning inside the area with priority 3.
I also swapped the mobs flag on both area's so mobs would spawn in the area with priority 3 and not in area with priority 1, and they did.
(entities are still able to walk in and out the area's regardless of the flags, that is normal behavior just not to be mistaken).

**Comment by dearminder** [comment]
I will later also try it on my own with fresh settings and fresh areas and maby I will findout what causing it

**Comment by dearminder** [comment]
Ok so, I wanted to test it on fresh from last phar, I was also thinking that maby its working only for square an square and i use sphere and square, nope still didnt work, i have no idea how to make it properly works

**Comment by genboy** [comment]
Hi @dearminder, thank you for testing, cube or sphere should not matter but it is a good idea to check that, i will look it up and test again. I'm in progress with the animals and mobs flags to allow slapper entities and will take the priority checks along. 
I'll fill you in on the progress in the next couple of days.

**Comment by genboy** [comment]
@dearminder whoops sorry for getting back so late. Hope coouple of weeks i have more time for fixing plugin bugs.
Have you been able to use the area priority function correctly?
I noticed a lot of other bugs in Festival 2.1.0 so i'll have to do an update soon

**Comment by dearminder** [comment]
Unfortunately 2 Months ago I have abandoned my server project so I am unable to test it

**Comment by genboy** [comment]
@dearminder good to know!
Thank you for using and helping with the Festival plugin!
