### ISSUE TITLE
That thing...

### ISSUE THREAD

**Issue by MateiGamingYTB** [genboy/Festival#22]
that thing in name with 100% health is from this plugin or?

**Comment by genboy** [comment]
@MateiGamingYTB it should not be, think it's is from something else. 
percentages are not used in Festival (yet).  Which version do you use? Always into review the code, maybe i missed a typo

**Comment by MateiGamingYTB** [comment]
latest

**Comment by mote166** [comment]
this doesn't happen to me so i don't think its caused by this plugin

**Comment by genboy** [comment]
@mote166 good to know, thank you!

_If you like v1.0.4-11 please leave a thumb up at [poggit](https://poggit.pmmp.io/p/Festival/1.0.4-11)  to help getting the Festival plugin approved, thank you!_

**Comment by MateiGamingYTB** [comment]
i founded, its not from your plugin, sorry for disturbing.
