### ISSUE TITLE
Exiting the Area message

### ISSUE THREAD

**Issue by BootheBoys** [genboy/Festival#221]
I made an area that stops on the ground, and it does not go into the ground any. This means that if I allow players to break blocks in that area, they could not break the floor. 

Ok, so now to the problem: Whenever someone stands on soul sand on the floor, it says they are leaving the area, because as you know, soul sand is slightly lower. I have to have soul sand there, and I really need my area to be there too.

Should I toggle the enter & leave messages in the config, or is there any chance of you "fixing" this, although it isn't necessarily a bug.. it's like a half bug.. xD

**Comment by genboy** [comment]
Hi @BoothebBoys, for this i made the y-scale option. It's n experiment;
/fe scale <areaname> <up/down> <int 0-9999> (9999 is unlimited) or see the area management menu

**Comment by BootheBoys** [comment]
Okay, but say I wanted the players to be able to break the blocks inside of the area.. would the floor still be unbreakable? Or does the scaling option only move the messages down and up? 

I can explain more if I am confusing :p

**Comment by genboy** [comment]
Hi @BootheBoys, maybe you can create another area to protect the floor blocks?
The y-scaling streches the area verticaly up and down. Sphere then  area's become cilinders.
If you know the diameter or radius you might be able to place two cilinder area's on top of each other just overlapping in the floor of the cilinder/sphere area. Hope  this is a solution for you, cheers1

**Comment by genboy** [comment]
I'm considering to split up the edit-flag in separate place and break actions
