### ISSUE TITLE
Cant build or break anywhere

### ISSUE THREAD

**Issue by diamondkorben** [genboy/Festival#222]
I made a spawn and it mad the whole world unbreakable unless you have op

**Comment by genboy** [comment]
Hi @diamondkorben, which Festival version are you using? 
You might first want to check the menu level manager to disable (not use flags)  or set the flags for that specific level.
In image below the flags are used for the level named 'world' and players are not allowed to break things cause the 'edit' flag is on.
![level manager](https://camo.githubusercontent.com/d3ea85434ebcbdf39dd51d01f994379d78f6b5ce/68747470733a2f2f67656e626f792e6e65742f77702d636f6e74656e742f75706c6f6164732f323031392f30372f6d616e6167655f6c6576656c5f6f7074696f6e2e6a7067)

A new area in this level will use the level flag settings as default, you can change them with the menu area manager or cmd (/fe 'flagname' 'areaname')

Please elaborate your situation a bit more for further help, thank you.

**Comment by diamondkorben** [comment]
Ok i will try that
