### ISSUE TITLE
Midair Area Creation

### ISSUE THREAD

**Issue by BootheBoys** [genboy/Festival#225]
I don't like having to place down the block to select pos1 and pos2, and I would much rather be able to fly to the position and set it where my player body is. It is a lot faster for me this way!

**Comment by genboy** [comment]
Nice idea, so you do not have to hit any block but it just catches your position, that might be possible, let me think about that a bit.

**Comment by genboy** [comment]
@BootheBoys Here's a [dev update](https://poggit.pmmp.io/r/70702/Festival_dev-111.phar) including tab positions in midair (holding the magic item or in command mode /pos1, rad etc.)

**Comment by genboy** [comment]
Introduced in version 2.1.2
