### ISSUE TITLE
Area Whitelist isn’t working 

### ISSUE THREAD

**Issue by kevinishawesome** [genboy/Festival#227]
When I set prevent edit to true, and add a few people to Whitelist, it doesn’t work, they still can’t edit it.. unless I turn off the flag..

**Comment by genboy** [comment]
Hi @kevinishawesome, I'll do some tests with the whitelist functions to fix it, give you an update when ready.  Thank for sharing this,

**Comment by genboy** [comment]
Yes @kevinishawesome , i'm testing and see that the whitelist is not saved correctly. I'll see to fix this asap.

**Comment by genboy** [comment]
Hi @kevinishawesome, the bug is fixed so the menu is saving whitelisted players correctly.
A Festival dev-version is ready for download at [poggit](https://poggit.pmmp.io/ci/genboy/Festival/Festival) Cheers!

**Comment by kevinishawesome** [comment]
That’s awesome!
