### ISSUE TITLE
Players are able to place Paintings 

### ISSUE THREAD

**Issue by kevinishawesome** [genboy/Festival#229]
Players cannot place any blocks, editing is enabled, but they are able to place paintings somehow, all over the place! 

Please look into this ..

Steps To Reproduce 

- Turn edit on areas or universal 
- Try placing paintings on these areas or universal

**Comment by genboy** [comment]
Hi @kevinishawesome, good to know, i'll check and fix this asap

**Comment by kevinishawesome** [comment]
Thanks a lot as always, your previous whitelist fix is working Beautifully now, hopefully you’ll get to this one too!

**Comment by genboy** [comment]
@kevinishawesome the paintings in pmmp do have some issues. It are entities attached on a blockside and not completely implemented in pmmp. 

While i'm still looking for the best solution for paitings i tested and made an update at [poggit dev](https://poggit.pmmp.io/ci/genboy/Festival/Festival) which prevents placing paintings under edit flag, but breaking is still possible.

**Comment by kevinishawesome** [comment]
Great! Placement matters, because some users get a hold items using switches on windows 10, and this guy just placed it almost everywhere he could till I got to him. Thank you for providing a temporary fix for this issue!

**Comment by genboy** [comment]
@kevinishawesome you are welcome. It is good to know the exact problem and how this helps you as a user. I'll keep this issue open untill not-breaking the paintings is also part of the edit flag function. Good luck with your sever, cheers!

**Comment by genboy** [comment]
@kevinishawesome the complete fix for testing painting protection is available at [poggit](https://poggit.pmmp.io/ci/genboy/Festival/Festival). You can close this issue if it works for you. Cheers!

**Comment by genboy** [comment]
@kevinishawesome the complete fix for testing painting protection is available at [poggit](https://poggit.pmmp.io/ci/genboy/Festival/Festival). You can close this issue if it works for you. Cheers!

**Comment by kevinishawesome** [comment]
Works! Thanks!
