### ISSUE TITLE
enter/leave msg

### ISSUE THREAD

**Issue by treehousemc1** [genboy/Festival#23]
i tried  
/fe flag (area name) msg false  
but still didnt works pls help

**Comment by genboy** [comment]
Hi @treehousemc1, 
To hide area messages for **regular players** please use
/fe flag<areaname> msg **true**
/fe msg<areaname> **true**
(fast toggle: /fe msg<areaname>)

I think you are an op :) - flags are for regular players
For ops please check your config.yml [#](https://github.com/genboy/Festival/blob/master/resources/config.yml) for second default option Msgdisplay;
off: area messages are hidden for all player types (unless msg flag is true)
op: area messages are always visible to ops if whitelisted to the area
on: ops will always see the areaa messages (disregarding the msg flag)

Hope this helps

**Comment by treehousemc1** [comment]
I want hide it from anyone. use off? But ppl who enter/leave still can see it

**Comment by treehousemc1** [comment]
not working..

**Comment by treehousemc1** [comment]
do u got twitter or etc so we can chat easy

**Comment by genboy** [comment]
@treehousemc1 can you share more info or is the issue resolved?
I've checked but can not reproduce your issue

**Comment by treehousemc1** [comment]
Solved thx
