### ISSUE TITLE
Level flags control

### ISSUE THREAD

**Issue by genboy** [genboy/Festival#230]
UI configuration to set overall options and default flags for levels and area's
![festival-set-configs-default-flags](https://user-images.githubusercontent.com/30810841/63712052-26bd2100-c83d-11e9-82f0-5ed7f03312f4.gif)

Turn on level flag control to use the level flags (instead of defaults)
![festival-use-level-flags](https://user-images.githubusercontent.com/30810841/63712056-291f7b00-c83d-11e9-9209-2dbb66c163fe.gif)

**Comment by genboy** [comment]
hi @Verox001 here are 2 small gifs on Festival configuration and turn on/off level flag usage

**Comment by TheGamerz13** [comment]
@genboy when i open the level ui flag it crashed me.
