### ISSUE TITLE
"fall" flag isn't disabling fall damage within area.

### ISSUE THREAD

**Issue by itzfrozt** [genboy/Festival#231]
basically as the title says, the "fall" flag is not disabling the fall damage or the defined area at all, not sure why, but it should be working and it isn't.

**Comment by genboy** [comment]
Hi @itzfrozt thank you for reporting, i'll check soon what is wrong

**Comment by genboy** [comment]
@itzfrozt an error with the Fall flag is fixed, latest update available at [poggit dev](https://poggit.pmmp.io/ci/genboy/Festival/Festival)

**Comment by itzfrozt** [comment]
works perfectly, thank you!
