### ISSUE TITLE
Probably already fixed: Slappers

### ISSUE THREAD

**Issue by itzfrozt** [genboy/Festival#236]
I know there is code in the festival.php for slappers to work and to bypass the mobs/animals flag, but everytime i made a slapper as a "player" it deletes, but saving it as a "horse" and scaling it to 0 has a chance of deleting. sorry for bothering you so much, i don't know if there is anything i can do, but if you can help, that would be very appreciated, thank you!

**Comment by genboy** [comment]
Hi @itzfrozt , i made a dev update when i heard about this problem in Dev #100. Actually still testing. Latest update Dev #103 has the unchanged slapper code. 
Did this error occur with version [Dev #100 - 103](https://poggit.pmmp.io/ci/genboy/Festival/Festival)?

**Comment by itzfrozt** [comment]
@genboy actually fixed it, all i had to do was update slapper and i downloaded the new festival-dev version. thank you for everything tho!!!
