### ISSUE TITLE
NoFallDamage still broken on latest release/latestdev

### ISSUE THREAD

**Issue by itzfrozt** [genboy/Festival#242]
No fall damage still not working on regions without "hurt" flag enabled, just realized after i went to make a floating spawn.

**Comment by genboy** [comment]
@itzfrozt thank you, good to know, i will check this soon to fix it

**Comment by itzfrozt** [comment]
here is the video of it not working for me

[fall damage not working video flv.zip](https://github.com/genboy/Festival/files/3609890/fall.damage.not.working.video.flv.zip)

**Comment by genboy** [comment]
hi @itzfrozt sorry for taking so lang, i've seen your vid and when i had time i tested a lot of times to reproduce this on my test server, without luck finding the error. Could you email me a copy of the areas.json and levels.json files and the name of the area (s) where the fall damage problem occurs?
I also noticed a lot of other bugs in Festival 2.1.0 so i'll have to do an update soon.

**Comment by genboy** [comment]
@itzfrozt sorry it took so long, falldamage is fixed now and ready for further testing in [latest dev update](https://poggit.pmmp.io/ci/genboy/Festival/Festival/105)
