### ISSUE TITLE
Turn off default flags

### ISSUE THREAD

**Issue by eliassaliba12** [genboy/Festival#243]
I want to use this plugin only for areas and not for level usuage i know i can turn iff flags in worlds but i run a skyblock plugin so eash player that join have a world for him so it will be impossible to do

**Comment by eliassaliba12** [comment]
Is there a way to turn off default flags and only keep the area flags

**Comment by genboy** [comment]
Hi @eliassaliba12, can you try to set levelcontrol="off" in festival/config.json file and see if the new worlds do copy this config? (new levels should have 'use the level flags' off by default)
