### ISSUE TITLE
flight flag problem

### ISSUE THREAD

**Issue by Kjenium** [genboy/Festival#244]
flight flag doesn't work. People can fly even if you put flight flag to false.  Also drop and the other flags don't work i tried to drop without op permissions and i could. Maybe I'm doing something wrong but I don't think so.

**Comment by mote166** [comment]
did u check that ur not whitelisted in that area ? cuz it automatically whitelists u when u create an area

**Comment by Kjenium** [comment]
I'm using level setup, no regions. So there's no whitelist I think.

**Comment by genboy** [comment]
@Kjenium can u check in level management for the specific level if 'use level flags' is on? then the flags in that level should be active. [like here](https://github.com/genboy/Festival/issues/244) 
To prevent flying the flight flag toggle should be on (right) 

sorry for this late reply

**Comment by mote166** [comment]
@genboy i have a question, does making alot or a huge areas of festival eat the server's ram or is it optimised not to ?

**Comment by mote166** [comment]
also there's a feature request i didn't feel it was worth making an issue for, make it so when the command is ran by console it doesn't appear to all the ops, like for ex if i put in area enter event /effect command every time a player triggers it all ops get the message of him taking the effect and thats a spam cuz its meant for vips and they are alot .

**Comment by genboy** [comment]
@mote166 good questions. optimised no sorry.
 Mainly because it runs through the area's list each onmove player to detect players in area's, with large amount of area's or with large amount players in large area's this might start using to much ram. I have not been able to test something like that with many players..

Your feature request is valuable, i'm not sure i can manage but will try to remove the command trigger spam.

**Comment by mote166** [comment]
thanks for pointing that out ill keep that in mind.

**Comment by mote166** [comment]
one last question, im currently using version 2.0.1 i never updated cuz i was afraid of new bugs coming out of new builds but it seems like there are none currently, the question is if i update it right now should i do some steps to keep all data from disappearing or for the new features to function correctly or should i just replace the plugin and thats it?

**Comment by genboy** [comment]
Hi @mote166, from 2.0.1 to 2.1.0 there should be no breaking changes but please always keep a copy of your areas.json file as a backup. 
Since version 2 also backup config.json and levels.json.

**Comment by Kjenium** [comment]
> @Kjenium can u check in level management for the specific level if 'use level flags' is on? then the flags in that level should be active. [like here](https://github.com/genboy/Festival/issues/244)
> To prevent flying the flight flag toggle should be on (right)
> 
> sorry for this late reply
Everything is active but still not work

**Comment by genboy** [comment]
Hi @Kjenium, sorry for my late reply, to single out some problems with flight flag a few questions;
- What Festival version do you use
- Do you use other plugins (that might have to do something with flight/fly)

**Comment by Kjenium** [comment]
I used last version on poggit when I opened this issue. So 2.1.0 or 2.0.0 i don't remember because I removed the plugin rn. I only use essentialspe that manages fly
