### ISSUE TITLE
Having trouble with the plugin

### ISSUE THREAD

**Issue by codcrusher12** [genboy/Festival#271]
The plugin works great it lets me do everything i want only one problem. every time i reload or restart my server every cube i made gets deleted.

**Comment by genboy** [comment]
Hi @codcrusher12 thank you for sharing your experience and dificulties. 
If i understand correctly the sphere areas do remain after restart. 
Could you look into the areas.json code if the areas are really gone?

**Comment by codcrusher12** [comment]
Hello I think it was cause my world was corrupt so i switched worlds and
its working but not priority isn't working. As im trying to put a pvp spot
in spawn and it will not work

**Comment by genboy** [comment]
Hi @codcrusher12, this spawn, is it a festival Area or is it the original world spawn area? If it's the regular spawn area the festival area (pvp) will not overwrite the spawn protection (regardless the priority).
