### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by creeperplayer20** [genboy/Festival#272]
hello again, i want to ask you if i can help you with translation to my language "Czech"

**Comment by genboy** [comment]
Hi @creeperplayer20 would be really nice to add Czech language. Translations are kept in separate .json files. There is a [translations branch](https://github.com/genboy/Festival/tree/Translations/resources) setup for this, if you use github you can fork this, copy the file en.json (or other), rename it cs.json (i think 'cs' is official for Czech is it?), edit the translation strings and send a pull request. 
You can also just copy the code from [en.json](https://github.com/genboy/Festival/blob/stable/resources/en.json) paste it in a textfile and send it to msg@genboy.net or attach it in this an (this) issue. Thank you!
