### ISSUE TITLE
Players (and other no-ops) cant break&build blocks

### ISSUE THREAD

**Issue by PetyXbronCZ** [genboy/Festival#282]
So....
I very unhappy
bcause i installed festival and then..
just all players cant build their houses in plots.... and cant break blocks in wild!
Maybe I set somethink wrong in config.yml but I dont really know what is wrong...
So I had to uninstall the plugin.. and Im very sad... bcause i need residents in survival you know...
pls reply, waiting :)

(by the way, do you have discord or something where I can contact you without these form?)
- Thanks, PetyXbron, owner of RP Craft

**Comment by genboy** [comment]
Hi, hope we can fix this. 
I think you need to look at the level(world) flags.

ingame command '/fe menu'
> select level management

![](https://camo.githubusercontent.com/429efbc124f1a9865c00386df45edaf1dc725103/68747470733a2f2f67656e626f792e6e65742f6d696e6563726166742f77702d636f6e74656e742f75706c6f6164732f323031392f30362f6d616e616765725f73746172742e6a7067)

> then select correct level and then turn 'edit' flag off, or turn 'level options' off

![](https://camo.githubusercontent.com/a8d696fa936d029db181ee1cf43255f59808cdc6/68747470733a2f2f67656e626f792e6e65742f6d696e6563726166742f77702d636f6e74656e742f75706c6f6164732f323031392f30372f6d616e6167655f6c6576656c5f6f7074696f6e2e6a7067)

If not possible ingame can you send or show me the configs (or only the world defaults part).
Comment here is fine or msg@genboy.net 
(or [discord](https://discord.com/invite/JFYeqYn) but i'm not that much active on discord)

**Comment by PetyXbronCZ** [comment]
Yeah, thanks, sorry for late reply.
I will try!

**Comment by janiiik** [comment]
had same issue, turning edit to off solved issue.
