### ISSUE TITLE
Flying in survival mode

### ISSUE THREAD

**Issue by RoccoGermani** [genboy/Festival#285]
I was planning to use this plugin in order to create designated pvp zones on my server but I have encountered an issue where it is allowing non OP players to fly in survival mode. I can't have this happening so I removed the plugin, hopefully temporarily. Is there a way to disable this flying in survival? Or is it a bug?

**Comment by genboy** [comment]
Hi @RoccoGermani thank you asking, sorry i'm a bit late in response. 
For the Festival flags there are like 3 config levels; 0 full game config, 1 level config and 2 area config. The combination of 3 levels with all flags makes keeping track of settings a bit complicated, i noticed myself. That is why i made it so world- and level- flight functionality can be turned off. 

I do not know your current config settings, maybe you can first disable (flight control toggle to the left) flight control in the configurations 
![](https://camo.githubusercontent.com/627482e2ef16aee72d8369392333992231fd67af/68747470733a2f2f67656e626f792e6e65742f6d696e6563726166742f77702d636f6e74656e742f75706c6f6164732f323031392f30362f6d616e616765725f636f6e66696775726174696f6e2e706e67)

and manage levels turn level option off  (flight control toggle to the left)
![](https://camo.githubusercontent.com/a8d696fa936d029db181ee1cf43255f59808cdc6/68747470733a2f2f67656e626f792e6e65742f6d696e6563726166742f77702d636f6e74656e742f75706c6f6164732f323031392f30372f6d616e6167655f6c6576656c5f6f7074696f6e2e6a7067)

With this you can test and evaluate your flag settings on area's, hope this helps. Cheers!
