### ISSUE TITLE
russian lang

### ISSUE THREAD

**Issue by maclarens** [genboy/Festival#286]
i correct russian lang and fix many errors

{
    "language-name": "Russian",
    "language-selected": "Русский",

    "enabled-console-msg": "Плагин теперь включен, выбран русский, (переключить язык  /fe lang <ru/en/nl/es/pl/fr>).",

    "cmd-ingameonly-msg": "Только в игре.",
    "cmd-unknown-msg": "Неизвестная команда плагина",
    "cmd-noperms-msg": "Нет прав на эту команду",
    "cmd-noperms-subcommand": "У вас нет разрешения на использование этой подкоманды.",

    "pos-select-active": "Процесс выбора уже запущен!",
    "select-both-pos-first":"Пожалуйста, выберите две позиции для этого.",
    "pos1": "позиция 1",
    "pos2": "позиция 2",
    "make-pos1": "Сломайте блок для установки pos1.",
    "make-pos2": "Сломайте блок для установки pos2, завершающую точку в кубическом привате.",
    "make-radius-distance": "Сломайте блок для установки pos2, чтобы установить радиус для сферического привата.",
    "radius-distance-to-position": "Дистанция радиуса до позиции",
    "make-diameter-distance": "Сломайте блок для установки pos2, чтобы установить диаметр для сферического привата.",
    "diameter-distance-to-position": "Дистанция диаметра до позиции",
    "give-area-name": "Пожалуйста, укажите название для этого привата. Использование: /fe create <имя-привата>",

    "in-unknown-area": "Вы находитесь в неизвестном привате",

    "area": "Приват",
    "areas": "Приватах",
    "level": "Мир",
    "levels": "Миров",
    "player": "Игрок",
    "players": "Игроки",
    "the-area": "Приват",
    "the-level": "Мир",
    "cube-area-created": "Кубический приват создан!",
    "sphere-area-created": "Сферический приват создан!",
    "created-by":"Создано",
    "area-here": "Тут запривачено",
    "area-no-area-available": "Нет доступных приватов",
    "area-no-area-to-edit": "Приваты отсутствуют, которые вы можете редактировать",
    "area-name-excist": "Приват с таким именем уже есть.",
    "area-not-excist": "Приват не существует.",
    "cannot-be-found": "Нечего не найдено.",
    "area-list" : "Список Приватов",
    "players-in-area": "Игроки в привате",
    "area-whitelist": "Белый список",
    "area-no-commands": "Приват не имеет команд",
    "player-has-been-whitelisted": "был занесен в белый список",
    "player-allready-whitelisted": "уже в белом списке",
    "player-has-been-unwhitelisted": "был удален из белого списка",
    "player-allready-unwhitelisted": "уже удален из белого списка",
    "whitelist-specify-action": "Пожалуйста, используйте следующие команды: /area whitelist <add/list/show/remove(del,delete)> <имя-игрока> и <название-привата>",
    "whitelist-specify-for-area": "Пожалуйста используйте в командной строке: /area whitelist <add/list/show/remove(del,delete)> <имя-игрока> и <название-привата>",

    "area-floating-titles": "Заголовки привата",

    "name-saved": "имя сохранено как",
    "name-write-usage": "Назначьте новое имя: /fe rename <имя-привата> и <своё-имя>",
    "name-specify-area": "Пожалуйста, укажите приват для переименования: /fe rename <имя-привата> и <новое имя привата>",
    "name-specify-to-area": "Пожалуйста используйте в командной строке: /fe rename <имя-привата> и <новое имя>",

    "desc-saved": "описание сохранено.",
    "desc-write-usage": "Пожалуйста, напишите описание: /fe desc <имя-привата> установить <..>",
    "desc-specify-area": "Пожалуйста, укажите приват чтобы отредактировать описание: /fe desc <имя-привата> set <ваше описание>",
    "desc-specify-set-area": "Пожалуйста, используйте 'set' для следующих команд: /fe desc <имя-привата> set <ваше описание>",

    "priority-saved": "приоритет сохранен.",
    "priority-specify-set-area":  "Пожалуйста, используйте 'set' для следующих команд: /fe priority <имя-привата> set <целое 0-999>",
    "priority-write-usage": "Пожалуйста, назначьте число: /fe priority <имя-привата> set <число 0-999>",
    "priority-number-usage": "Пожалуйста, введите число, 0 по умолчанию, 1 - 999 назначает более высокий приоритет: /fe priority <имя-привата> set <число 0-999>",
    "priority-specify-area": "Пожалуйста, укажите приват для редактирования приоритета: /fe priority <имя-привата> set <число 0-999>",

    "scaling-height-saved": "высота  привата сохранена.",
    "scaling-floor-saved": "площадь привата сохранена.",
    "scaling-specify-set-area":  "Пожалуйста, используйте «вверх»/«вниз» в этой команде: /fe scale <имя-привата> <up/down> <число 0-9999>",
    "scaling-write-usage": "Пожалуйста, укажите количество блоков вверх или низ: /fe scale <имя-привата> <up/down> <число 0-9999>",
    "scaling-number-usage": "Пожалуйста, укажите количество блоков, 0 по умолчанию, 1 - 9998 назначает масштабирование, 9999 неограниченно: /fe scale <имя-привата> <up/down> <число 0-9999>",
    "scaling-specify-area": "Пожалуйста, укажите приват для редактирования масштабирования (вверх/вниз) - (top/bottom): /fe scale <имя-привата> <up/down> <число 0-9999>",

    "area-deleted": "приват удалён!",
    "deleted-by":"удалён",
    "specify-to-delete":"Пожалуйста, выберите приват для удаления.",

    "flag": "Флаг",
    "flags": "Флагов",
    "flag-not-found-list": "Флаг не найден. (Флаги: hurt, pvp, flight, edit, touch, animals, mobs, effect, msg, pass, drop, tnt, shoot, hunger, perms, fall)",
    "flag-not-specified-list": "Пожалуйста, укажите флаг. /fe <имя-флага> <имя-привата> (Имена флагов: hurt, pvp, flight, edit, touch, animals, mobs, effect, msg, pass, drop, tnt, shoot, hunger, perms, fall)",
    "specify-to-flag": "Пожалуйста, укажите приват, который вы хотите выбрать.",

    "tp-to-area-active": "Вы телепортируетесь в приват",
    "specify-excisting-area-name": "Укажите существующее название привата: получить список приватов (/fe list)",

    "cmd": "команда",
    "cmds": "команд",
    "cmd-id": "Идентификатор команды",
    "cmd-list": "Команды в привате",
    "-event": "-событие",
    "set-for-area": "установить для привата",
    "added-to-area": "добавлено в приват",
    "allready-used-for": "уже используется для ",

    "allready-set-for-area": "уже установлен для привата",
    "edit-id-or-other": "Отредактируйте этот идентификатор или используйте другой идентификатор",
    "cmd-specify-id-and-command-usage": "Укажите идентификатор команды и команду для добавления: /fe command <имя-привата> <add(enter/center/leave)/list/edit/del> <Идентификатор команды> <Имя команды>",
    "cmd-valid-areaname": "Приват не найден, пожалуйста, введите правильное имя: /fe command <имя-привата> <add(enter/center/leave)/list/edit/del> <Идентификатор команды> <Имя команды>.",

    "cmd-id-not-found": "Идентификатор команды не найден. Используйте команды для получения списка: /fe command <имя-привата> list",
    "cmd-specify-id-to-delete": "Пожалуйста, укажите идентификатор команды для удаления: /fe command <имя-привата> del <Идентификатор команды>",
    "cmd-specify-action": "Пожалуйста, добавьте действие для выполнения с командой: /fe command <имя-привата> <add/list/edit/del> <Идентификатор команды> <Имя команды>.",

    "event": "событие",
    "event-is-now": "новое событие",
    "change-failed": "Изменить не удалось!",

    "not-available": "отсутствуют",
    "deleted": "удалить",
    "select-and": "Выбрано",
    "select-in": "внедрено в",
    "select-yes": "Да",
    "select-no": "Нет",
    "status-on": "включить",
    "status-off": "выключить",
    "set-to": "установлена на",
    "for-area": "для привата",
    "number-to-write": "Назначить номер",

    "all-players-are-save": "Все игроки сохраняются в этой области!",
    "no-pvp-area": "Здесь PVP выключено!",
    "no-flight-area": "Режим полета тут выключен!",
    "flight-area": "Полеты разрешены здесь!",
    "no-shoot-area": "НЕТ Съемки здесь",

    "leaving-area": "покинул",
    "enter-area": "вошёл на ",
    "leaving-center-area": "Покидание центра привата",
    "enter-center-area": "Введите центр привата",
    "cannot-enter-area": "Вы не можете войти в приват",
    "cannot-leave-area": "Вы не можете покинуть приват",
    "enter-barrier-area": "только мимо барьера!",

    "option-missing-in-config": "опция отсутствует в config.yml, теперь установлена на",
    "flag-missing-in-config": "флаг по умолчанию отсутствует, теперь установлен",
    "barrier-is-passage-flag": "Использовался старый конфиг Барьера, теперь установлен на «false»; пожалуйста, переименуйте «Барьер» в «true» в config.yml",
    "no-is-falldamage-flag": "Использовалась старая конфигурация NoFalldamage, теперь она установлена на «false»; пожалуйста, переименуйте «NoFalldamage» в «Falldamage» в config.yml",
    "option-see-configfile": "пожалуйста, смотрите оригинальные конфиги в /resources/config.yml",

    "compass-dir-wsp": "Направление компаса установлено на точку появления в мире",
    "compass-dir-area": "Направление компаса установлено на приват ",
    "compass-dir-notset": "Направление не может быть установлено",
    "compass-inthisworld": "В этом мире ",
    "compass-level-reset": "Сброс направления компаса",

    "ui-compass-title": "Установить направление компаса",
    "ui-compass-use-compass": "Использовать направление компаса",
    "ui-compass-selected-wsp": "Выбранная точка появления в мире",
    "ui-compass-selected-this": "выбранный ",
    "ui-compass-not-found": "Выбранный приват не найден",
    "ui-compass-wsp-default": "Точка появления в мире (по умолчанию)",

    "ui-festival-manager": "Управление",
    "ui-new-area-setup": "Новая настройка привата",
    "ui-select-an-option": "Выберите опцию",
    "ui-select-area": "Отметьте приват",
    "ui-go-back": "Назад",
    "ui-saved": "сохранён!",
    "ui-new": "Новый",
    "ui-deleted": "Удалить!",
    "ui-not-found": "Не найдено!",
    "ui-try-again": "Попробуйте еще раз",

    "ui-area-teleport": "Телепорт привата",
    "ui-teleport-to-area": "Телепорт в приват",
    "ui-teleport-select-destination": "Выберите точку телепорта привата",
    "ui-tp-to-area": "Переход в приват",

    "ui-area-management": "Управление приватом",
    "ui-area-manager": "Руководитель фестиваля",
    "ui-create-area": "Создать новый приват",
    "ui-edit-area-options": "Редактировать флаги и опции",
    "ui-edit-area-commands": "Редактировать команды",
    "ui-edit-area-whitelist": "Редактировать белый список",
    "ui-delete-area": "Удалить приват",

    "ui-manage-area": "Управление приватом",
    "ui-manage-areas": "Управление приватами",
    "ui-name": "Имя",
    "ui-description": "Описание",
    "ui-priority": "Приоритет",
    "ui-select-edit-area": "Выберите приват для редактирования",
    "ui-cmd-id-not-found": "Идентификатор команды не найден! Попробуйте еще раз или выберите другой вариант",
    "ui-cmd-empty-not-saved": "Пустая команда не сохранилась! Попробуйте еще раз или выберите другой вариант",

    "ui-scale-height": "Высота привата",
    "ui-scale-floor": "Глубина привата",

    "ui-area-maker": "Создание привата",
    "ui-select-new-area-type": "Выберите тип создания привата:",
    "ui-make-cube-diagonal": "Куб - выберите 2 диагональных положения",
    "ui-make-sphere-radius": "Радиус сферы - выберите центр и радиус расстояния",
    "ui-make-sphere-diameter": "Диаметр сферы - выберите 2 положения диаметра",
    "ui-area-name": "Название привата",
    "ui-area-desc": "Описание привата",
    "ui-new-area-named": "Новое имя привата",
    "ui-created": "создан!",
    "ui-tab-pos1-diagonal": "Диагональная позиция для новой области куба",
    "ui-tab-pos1-radius": "Центральная позиция для новой области сферы",
    "ui-tab-pos1-diameter": "Диаметральная позиция новой области сферы",

    "ui-manage-area-commands": "Управление командами привата",
    "ui-area-command-list": "Список команд привата",
    "ui-area-add-command": "",
    "ui-area-add-command-event": "Добавить тип события команды",
    "ui-area-add-new-command": "Добавить новую команду:",
    "ui-area-change-command": "Редактировать команду:",
    "ui-area-type-command-id-change": "",
    "ui-area-del-command": "Удалить команду:",
    "ui-area-type-command-id-del": "",

    "ui-manage-area-whitelist": "Управление белым списком",
    "ui-area-whitelist-saved": "Белый список сохранен!",
    "ui-whitelist-select-area": "Выберите приват для белого списка",
    "ui-formdate-not-available-try-again": "Данные формы повреждены или недоступны, пожалуйста, попробуйте еще раз.",
    "ui-areaname-allready-used-try-again": "Новое название привата неверное или уже используется. Пожалуйста, попробуйте другое имя:",

    "ui-delete-an-area":"Удалить приват",
    "ui-select-area-delete":"Выберите приват для удаления:",
    "ui-select-to-delete-area":"",
    "ui-delete-this-area": "! Удалить приват",
    "ui-gonna-delete-area": "Вы собираетесь удалить приват",

    "ui-level-management": "Управление миром",
    "ui-manage-levels": "Управлять мирами",
    "ui-level-select": "Выбор мира",
    "ui-select-level-edit": "Выберите мир для редактирования флагов",
    "ui-level-flag-management": "Управление флагами мира",
    "ui-level": "Мир",
    "ui-flags-saved": "флаг установлен и сохранен!",
    "ui-subtitle-level-options": "Варианты мира:",
    "ui-toggle-flag-control": "Использовать флаги мира",
    "ui-subtitle-level-flags": "Флаги мира:",

    "ui-config-management": "Конфигурация",
    "ui-festival-configuration": "Конфигурация плагина",
    "ui-config-flags-options": "Конфиги по умолчанию",
    "ui-config-msg-position": "Вывод сообщений привата в",
    "ui-config-msg-visible": "Сообщения привата видны",
    "ui-config-floating-titles": "Виден ли заголовки над приватом",
    "ui-config-auto-whitelist": "Добавлять автоматом в белый список",
    "ui-config-flight-control": "Управление полетом",
    "ui-config-action-itemid": "Предмет для вызова меню плагина привата",
    "ui-configs-saved": "Конфиги сохранены"
}

**Comment by genboy** [comment]
Hi @maclarens, thank you very much for posting the changes, i'll see to includes these in a dev version first for testing, will post the link here. If ok i'll put this in the stable  branch.
Thank you a lot for helping improving Festival, Cheers!

**Comment by maclarens** [comment]
no problem!if i find any error i will complement more..

**Comment by genboy** [comment]
The language works fine in the menu, uploaded in the dev-branch for testing.
https://poggit.pmmp.io/ci/genboy/Festival/Festival/dev:118
also have to fix those 307 lint problems

I do not speak russian, I did some checks with translators, I see you made the meaning more accurate. 
Wondering, does the word 'area' not translate that well to russian? 
Translation test of Приват to english gave me 2 words, 'private'  and 'plot'.
Would it be better to use the translation of 'section'?  

Anyways, thank you for the language update, hope to put it up to the next release soon (after 307 fixes :)

**Comment by maclarens** [comment]
area its приват in this situation with plugin! and if i say (literally translated)площадь russian not understain this :)with google translate lost many meaning in translate and not always suitable!
area it will become private in the future right?simpler and clearer change name just on private(Приват)!

**Comment by maclarens** [comment]
hello!Yep!i use this translate on my server !and everethyn its good.

**Comment by genboy** [comment]
Still works great, thank you!
