### ISSUE TITLE
Internal Server Error with ManyWorlds

### ISSUE THREAD

**Issue by realjaycg** [genboy/Festival#297]
After making a **/fe** area in a 2ndary ManyWorld(not default) the server will give you a Internal Server Error when  you type **/mw tp hgspawn** or if i try to teleport someone over after i make the are it will give me the ISE and i will get kicked but they will stay in the default world

 Video - https://www.youtube.com/watch?v=02Y0NIpYkvU

**Comment by genboy** [comment]
Hi @realjaycg, thanks for the on screen issue example. 
The /tp cmd used, is it from ManyWorlds or an other plugin like EssentialsPE? 
I will look up how commands can mixup other plugins commands, or how teleporting might get mixed up. As far as i understand you wanted to teleport from 1 world to another world, to it's spawnpoint to be precise, with /mw tp WORLDNAME. I wonder if this has something to do with Festival. I know there could be a problem if worlds are loaded and unloaded or renamed, because the areas are synced to levels. For Festival area teleport, can you see if this cmd works; /fe tp AREANAME 
Hope we can find out what's buggin, cheers!

**Comment by realjaycg** [comment]
@genboy if the log of the crash helps here
27.07 21:32:30 [Server] Server thread/CRITICAL Error: "Undefined property: pocketmine\network\mcpe\protocol\SetSpawnPositionPacket::$spawnForced" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 205
27.07 21:32:30 [Server] Server thread/CRITICAL #0 plugins/Festival.phar/src/genboy/Festival/Festival(1342): pocketmine\network\mcpe\protocol\DataPacket->__set(string[11] spawnForced, boolean 1)
27.07 21:32:30 [Server] Server thread/CRITICAL #1 src/pocketmine/plugin/MethodEventExecutor(42): genboy\Festival\Festival->levelChange(object pocketmine\event\entity\EntityLevelChangeEvent)
27.07 21:32:30 [Server] Server thread/CRITICAL #2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object genboy\Festival\Festival, object pocketmine\event\entity\EntityLevelChangeEvent)
27.07 21:32:30 [Server] Server thread/CRITICAL #3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityLevelChangeEvent)
27.07 21:32:30 [Server] Server thread/CRITICAL #4 src/pocketmine/entity/Entity(1891): pocketmine\event\Event->call()
27.07 21:32:30 [Server] Server thread/CRITICAL #5 src/pocketmine/Player(963): pocketmine\entity\Entity->switchLevel(object pocketmine\level\Level)
27.07 21:32:30 [Server] Server thread/CRITICAL #6 src/pocketmine/entity/Entity(1756): pocketmine\Player->switchLevel(object pocketmine\level\Level)
27.07 21:32:30 [Server] Server thread/CRITICAL #7 src/pocketmine/entity/Entity(1781): pocketmine\entity\Entity->setPosition(object pocketmine\level\Position)
27.07 21:32:30 [Server] Server thread/CRITICAL #8 src/pocketmine/entity/Entity(1872): pocketmine\entity\Entity->setPositionAndRotation(object pocketmine\level\Position, double 336.78863525391, double -15.600021362305)
27.07 21:32:30 [Server] Server thread/CRITICAL #9 src/pocketmine/Player(3915): pocketmine\entity\Entity->teleport(object pocketmine\level\Position, NULL , NULL )
27.07 21:32:30 [Server] Server thread/CRITICAL #10 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/command/subcommand/TeleportSubcommand(67): pocketmine\Player->teleport(object pocketmine\level\Position)
27.07 21:32:30 [Server] Server thread/CRITICAL #11 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/command/MultiWorldCommand(117): czechpmdevs\multiworld\command\subcommand\TeleportSubcommand->executeSub(object pocketmine\Player, array[1], string[8] teleport)
27.07 21:32:30 [Server] Server thread/CRITICAL #12 src/pocketmine/command/SimpleCommandMap(248): czechpmdevs\multiworld\command\MultiWorldCommand->execute(object pocketmine\Player, string[2] mw, array[1])
27.07 21:32:30 [Server] Server thread/CRITICAL #13 src/pocketmine/Server(1811): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[9] mw tp hg1)
27.07 21:32:30 [Server] Server thread/CRITICAL #14 src/pocketmine/Player(2310): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[9] mw tp hg1)
27.07 21:32:30 [Server] Server thread/CRITICAL #15 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(244): pocketmine\Player->chat(string[10] /mw tp hg1)
27.07 21:32:30 [Server] Server thread/CRITICAL #16 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
27.07 21:32:30 [Server] Server thread/CRITICAL #17 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
27.07 21:32:30 [Server] Server thread/CRITICAL #18 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
27.07 21:32:30 [Server] Server thread/CRITICAL #19 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
27.07 21:32:30 [Server] Server thread/CRITICAL #20 src/pocketmine/Player(3247): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
27.07 21:32:30 [Server] Server thread/CRITICAL #21 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
27.07 21:32:30 [Server] Server thread/CRITICAL #22 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 73.157.141.157 54005, object raklib\protocol\EncapsulatedPacket, integer 0)
27.07 21:32:30 [Server] Server thread/CRITICAL #23 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
27.07 21:32:30 [Server] Server thread/CRITICAL #24 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
27.07 21:32:30 [Server] Server thread/CRITICAL #25 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
27.07 21:32:30 [Server] Server thread/CRITICAL #26 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
27.07 21:32:30 [Server] Server thread/CRITICAL #27 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1595885550.5826)
27.07 21:32:30 [Server] Server thread/CRITICAL #28 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
27.07 21:32:30 [Server] Server thread/CRITICAL #29 src/pocketmine/Server(1588): pocketmine\Server->start()
27.07 21:32:30 [Server] Server thread/CRITICAL #30 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
27.07 21:32:30 [Server] Server thread/CRITICAL #31 src/pocketmine/PocketMine(304): pocketmine\server()
27.07 21:32:30 [Server] Server thread/CRITICAL #32 (11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)
27.07 21:32:30 [Server] Server thread/INFO realjaycg left the game
27.07 21:32:30 [Server] Server thread/INFO realjaycg[/------------------(my ip)] logged out due to Internal server error

**Comment by realjaycg** [comment]
@genboy if this helps (sorry for 2nd post)
27.07 21:32:30 [Server] Server thread/CRITICAL Error: "Undefined property: pocketmine\network\mcpe\protocol\SetSpawnPositionPacket::$spawnForced" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 205
27.07 21:32:30 [Server] Server thread/CRITICAL #0 plugins/Festival.phar/src/genboy/Festival/Festival(1342): pocketmine\network\mcpe\protocol\DataPacket->__set(string[11] spawnForced, boolean 1)
27.07 21:32:30 [Server] Server thread/CRITICAL #1 src/pocketmine/plugin/MethodEventExecutor(42): genboy\Festival\Festival->levelChange(object pocketmine\event\entity\EntityLevelChangeEvent)
27.07 21:32:30 [Server] Server thread/CRITICAL #2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object genboy\Festival\Festival, object pocketmine\event\entity\EntityLevelChangeEvent)
27.07 21:32:30 [Server] Server thread/CRITICAL #3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityLevelChangeEvent)
27.07 21:32:30 [Server] Server thread/CRITICAL #4 src/pocketmine/entity/Entity(1891): pocketmine\event\Event->call()
27.07 21:32:30 [Server] Server thread/CRITICAL #5 src/pocketmine/Player(963): pocketmine\entity\Entity->switchLevel(object pocketmine\level\Level)
27.07 21:32:30 [Server] Server thread/CRITICAL #6 src/pocketmine/entity/Entity(1756): pocketmine\Player->switchLevel(object pocketmine\level\Level)
27.07 21:32:30 [Server] Server thread/CRITICAL #7 src/pocketmine/entity/Entity(1781): pocketmine\entity\Entity->setPosition(object pocketmine\level\Position)
27.07 21:32:30 [Server] Server thread/CRITICAL #8 src/pocketmine/entity/Entity(1872): pocketmine\entity\Entity->setPositionAndRotation(object pocketmine\level\Position, double 336.78863525391, double -15.600021362305)
27.07 21:32:30 [Server] Server thread/CRITICAL #9 src/pocketmine/Player(3915): pocketmine\entity\Entity->teleport(object pocketmine\level\Position, NULL , NULL )
27.07 21:32:30 [Server] Server thread/CRITICAL #10 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/command/subcommand/TeleportSubcommand(67): pocketmine\Player->teleport(object pocketmine\level\Position)
27.07 21:32:30 [Server] Server thread/CRITICAL #11 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/command/MultiWorldCommand(117): czechpmdevs\multiworld\command\subcommand\TeleportSubcommand->executeSub(object pocketmine\Player, array[1], string[8] teleport)
27.07 21:32:30 [Server] Server thread/CRITICAL #12 src/pocketmine/command/SimpleCommandMap(248): czechpmdevs\multiworld\command\MultiWorldCommand->execute(object pocketmine\Player, string[2] mw, array[1])
27.07 21:32:30 [Server] Server thread/CRITICAL #13 src/pocketmine/Server(1811): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[9] mw tp hg1)
27.07 21:32:30 [Server] Server thread/CRITICAL #14 src/pocketmine/Player(2310): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[9] mw tp hg1)
27.07 21:32:30 [Server] Server thread/CRITICAL #15 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(244): pocketmine\Player->chat(string[10] /mw tp hg1)
27.07 21:32:30 [Server] Server thread/CRITICAL #16 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
27.07 21:32:30 [Server] Server thread/CRITICAL #17 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
27.07 21:32:30 [Server] Server thread/CRITICAL #18 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
27.07 21:32:30 [Server] Server thread/CRITICAL #19 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
27.07 21:32:30 [Server] Server thread/CRITICAL #20 src/pocketmine/Player(3247): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
27.07 21:32:30 [Server] Server thread/CRITICAL #21 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
27.07 21:32:30 [Server] Server thread/CRITICAL #22 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] ----------my ip 54005, object raklib\protocol\EncapsulatedPacket, integer 0)
27.07 21:32:30 [Server] Server thread/CRITICAL #23 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
27.07 21:32:30 [Server] Server thread/CRITICAL #24 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
27.07 21:32:30 [Server] Server thread/CRITICAL #25 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
27.07 21:32:30 [Server] Server thread/CRITICAL #26 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
27.07 21:32:30 [Server] Server thread/CRITICAL #27 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1595885550.5826)
27.07 21:32:30 [Server] Server thread/CRITICAL #28 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
27.07 21:32:30 [Server] Server thread/CRITICAL #29 src/pocketmine/Server(1588): pocketmine\Server->start()
27.07 21:32:30 [Server] Server thread/CRITICAL #30 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
27.07 21:32:30 [Server] Server thread/CRITICAL #31 src/pocketmine/PocketMine(304): pocketmine\server()
27.07 21:32:30 [Server] Server thread/CRITICAL #32 (11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)
27.07 21:32:30 [Server] Server thread/INFO realjaycg left the game
27.07 21:32:30 [Server] Server thread/INFO realjaycg[/--------------my ip] logged out due to Internal server error

**Comment by genboy** [comment]
Looks the same like below; occured when setting Festival level configuration. This did not happen befor with Festival v2.1.2 so looking for what changed in recent pmmp version(s).
2020-08-07 [16:25:37] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\SetSpawnPositionPacket::$spawnForced" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 205
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #0 plugins/Festival-2.1.2.phar/src/genboy/Festival/FormUI(885): pocketmine\network\mcpe\protocol\DataPacket->__set(string[11] spawnForced, boolean 1)
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #1 plugins/Festival-2.1.2.phar/src/xenialdan/customui/Form(48): genboy\Festival\FormUI->genboy\Festival\{closure}(object pocketmine\Player, array[22])
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #2 src/pocketmine/Player(3600): xenialdan\customui\Form->handleResponse(object pocketmine\Player, array[23])
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #3 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(264): pocketmine\Player->onFormSubmit(integer 2, array[23])
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #4 src/pocketmine/network/mcpe/protocol/ModalFormResponsePacket(49): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket)
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #6 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket)
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #8 src/pocketmine/Player(3247): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #9 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #10 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 83.84.181.236 64816, object raklib\protocol\EncapsulatedPacket, integer 0)
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #11 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #12 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #13 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #14 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #15 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1596817537.7835)
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #16 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #17 src/pocketmine/Server(1588): pocketmine\Server->start()
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #18 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[15] /home/gs-40310/, string[23] /home/gs-40310/plugins/)
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #19 src/pocketmine/PocketMine(304): pocketmine\server()
2020-08-07 [16:25:37] [Server thread/CRITICAL]: #20 (11): require(string[94] phar:///pro/bin/mcpe/pocketmine-stable-1.16.0/PocketMine-MP.phar/src/pocketmine/)

**Comment by genboy** [comment]
@realjaycg ok, yes it has to do with Festival compass usage in levels. So far i found this problem has to do with a spawnforced-variable that is used to reset the players spawn position/ compass direction. If the compass option for a level is turn off Festival will try to reset the player spawn position. 
I tested to turn on the level compass usage option (when editing a level) and then the error did not occure. 
So that is a temp solution. - i'm still digging to find the root cause of this problem

**Comment by realjaycg** [comment]
@genboy ok I dont really look at GitHub LOL but will try that, but we are using Festival over a SurvivalGames world rn

**Comment by genboy** [comment]
Same as #296, loosing the compass fnction in Festival fixed this error - [dev version #121](https://poggit.pmmp.io/ci/genboy/Festival/Festival/dev:121) .phar available
