### ISSUE TITLE
SPECIFIED WORLD AREA

### ISSUE THREAD

**Issue by mrpwes** [genboy/Festival#298]
Area Crossing Between 2 Worlds
```yml
#Ex// i set area to protect @HubWorld also @SurvivalWorld 
#When you are walking inside Survival World you gonna see tipmsg: entering Hub / leaving Hub
#But when you check /fe list per world it seem doesn't crossing.
#only 1 area showing but when you walk you can see @HubAreaFlags is working @SurvivalWorld
#Same Coordinates Protected

**Comment by mrpwes** [comment]
I restarted server and all goods
im not sure if its still in there

**Comment by mrpwes** [comment]
is the area support per world ?

**Comment by genboy** [comment]
Hi @mrpwes, thank you for reporting this issue. 
Please clarify a bit  '.. it seem doesn't crossing'; 
the area is not listed when using /fe list? or is the area damage-flag on and the area should have no passage?
Note; check for missing areas if the area data is available in the plugins/Festival/areas.json file.

**Comment by genboy** [comment]
Long time nog response, i hope all worked out well. See the [Festival Dev update](https://poggit.pmmp.io/ci/genboy/Festival/Festival/dev:121) for latest debugged version. Thank you for sharing your experience.
