### ISSUE TITLE
Allowed flight

### ISSUE THREAD

**Issue by chisi21** [genboy/Festival#310]
I don't understand why when I install this plugin, the player is always flying, I've tried disabling the fly settings, but it still doesn't work. is this a bug or my mistake during configuration? 

Thanks

**Comment by genboy** [comment]
![](https://camo.githubusercontent.com/3bdb240737e970f702ce736d4b7db669367f066caa9e7faebd2bca4bbddb3b1b/68747470733a2f2f67656e626f792e6e65742f6d696e6563726166742f77702d636f6e74656e742f75706c6f6164732f323031392f30362f6d616e616765725f636f6e66696775726174696f6e2e706e67)
Hi, sorry soooo late to respond. For testing for the rpoblem, you can let Festival not use flight option.
Can you try to turn of flight control in the configuration?
