### ISSUE TITLE
message

### ISSUE THREAD

**Issue by NGGNewGen** [genboy/Festival#34]
is there a way to send a command to the player that entered? because im trying to send a title and i dont know the variables
like for example:
When the player enters an area i want it to pop up with a title to the player saying "Entering Warzone"

**Comment by genboy** [comment]
Hi, targetting the player might be done with @p in the command (you may need another plugin for that at the moment, i still have to create a command string filter to do this inside Festival).
Does the area description that pops up with the area-onenter message not work for you? 
Can set it with /fe desc AREANAME DESCRIPTIONTEXTLINE

**Comment by genboy** [comment]
@NGGNewGen the Festival development branch now has the @p filter for commands to target players.
https://github.com/genboy/Festival/tree/development | https://poggit.pmmp.io/r/31830/Festival_dev-23.phar

**Comment by NGGNewGen** [comment]
Life Saver! Thank you!!

**Comment by NGGNewGen** [comment]
Just tried @p and it doesnt work :\

**Comment by genboy** [comment]
@NGGNewGen  Nice work, thank you for testing and PR. **I wonder why @p didn't work**, do you have an idea?

I like @p cause it is short and well known substitute, but i like {player} too so **would just implement both :) If I only knew what makes @p not wor**k (can add a config option to choose  notation type if needed)

**Comment by genboy** [comment]
updated with both {player} & @p 
[dev branch](https://github.com/genboy/Festival/commit/fae50ab909dc28d360a20749f2ece70562869d21) - [poggit phar](https://poggit.pmmp.io/r/32046/Festival_dev-25.phar)

**Comment by NGGNewGen** [comment]
Maybe it didnt work the first time because in pocketmine there isnt a @p variable so maybe it just didnt reconize players as @p?

**Comment by NGGNewGen** [comment]
Im just begining in coding so i dont know very much heh

**Comment by genboy** [comment]
@NGGNewGen 
Could you send me a list of your active plugins during testing?
Your intention worked out great i think, thank you.

---


It does not matter pmmp does not know any @p, as long as Festival does recognize the symbol or string we use AND other code/plugins do not interfere; 

basic idea is:
- the command string is a saved static variable waiting to be executed by a playerevent
- right before execution the command is put in the filter function to find out if part of the command is the string symbol ({player} or @p), and if so, only that moment the code knows the correct playername (from the event) to replace the symbol and execute on correct player.

Now if we find out if there is a hook (function to be called at a certain moment of pmmp code running) to be used after the festival event command code execution, this might be a problem related to @ not working ( and possible cheating in the area :)
or the @ might be used in some text coloring plugin or something and allready stripped out before festival code got to it.

**Comment by NGGNewGen** [comment]
Great to know! Thanks for informing me on this :) If there are any more errors i will let you know!
(Because i check for updates on this plugin every 2 to 3 days)
