### ISSUE TITLE
How to set non pvp/pvp area?

### ISSUE THREAD

**Issue by JamXDrew** [genboy/Festival#39]
How?

**Comment by genboy** [comment]
@JamXDrew 
Good question, very important! I'll have to check the code and fix that soon, thank you

**Comment by JamXDrew** [comment]
Oki thanks!

**Comment by NGGNewGen** [comment]
Jam for a short time you could just do an area flagged with god then the other area not flagged with god

**Comment by genboy** [comment]
God flag might be an option sometimes only,
I do understand the pvp importance, 
ie. if you want to make a team of players who still can get hurt by monsters and natural damage, but not by players in a certain area.

**Comment by JamXDrew** [comment]
Thanks!!

**Comment by genboy** [comment]
Ok, implemented PVP in [Festival2](https://github.com/genboy/Festival2) for testing now. 
First have to take a good look at [v1.0.5-12 latest dev](https://poggit.pmmp.io/babs/a66e) before adding the new PVP flag without to much changes/trouble for users.

Maybe anyone likes to try this, basics are still the same as v1.0.5.12;
[Festival2-master.zip](https://github.com/genboy/Festival/files/2065487/Festival2-master.zip)
[Festival_v2.0.0-12-dev.phar.zip](https://github.com/genboy/Festival/files/2065478/Festival_v2.0.0-12-dev.phar.zip)

**Comment by genboy** [comment]
Festival area PVP and Fly flags added for testing in v1.0.6-13-dev [github](https://github.com/genboy/Festival/tree/development) - [poggit](https://poggit.pmmp.io/ci/genboy/Festival/Festival). 
For development, if you can test let me know, i thought there is much lag but maybe it is just my test server / connection.
