### ISSUE TITLE
Suggestion BUG

### ISSUE THREAD

**Issue by SuperAdam47** [genboy/Festival#54]
Add Fire animation protect 
![image](https://user-images.githubusercontent.com/16169771/42463907-36ae0002-83b0-11e8-94d7-b33c7b0f7df1.png)

**Comment by SuperAdam47** [comment]
@genboy

**Comment by genboy** [comment]
@SuperAdam47  
Good idea, added to [the todo list](https://github.com/genboy/Festival/projects/1)

**Comment by genboy** [comment]
Hi @SuperAdam47, 
Fire is now extinguished when player does not get damage (aka. in area with god flag on)  
https://poggit.pmmp.io/ci/genboy/Festival/Festival
! i've not tested this dev poggit's .phar yet

Note - on lava or other fire hot blocks (constant fire trigger) the players fire is extinguished when leaving the blocks - fire is a particle animation on clientside and i think it would take to much memory (lag) for detecting and putting out fires on blocks that make the player burn.
(A 'fire flag' will take a bit more code study for me)

**Comment by SuperAdam47** [comment]
Good work.
