### ISSUE TITLE
Suggestion for better text design

### ISSUE THREAD

**Issue by SuperAdam47** [genboy/Festival#65]
![image](https://user-images.githubusercontent.com/16169771/43993680-386fd6fa-9d9a-11e8-86cf-1d2b35a4a194.png)
- It would be nice to add color and layout here.

**Comment by genboy** [comment]
Yes, i think about to how make the Festival text 'design' more attractive for ops.
i didn't get to it because I want someday to work with the native formApi to control and display area info.
