### ISSUE TITLE
add /fe flag arena bow on (projectiles)

### ISSUE THREAD

**Issue by SuperAdam47** [genboy/Festival#66]
![image](https://user-images.githubusercontent.com/16169771/43995235-27ab1528-9db3-11e8-97fb-b72f3aa2e278.png)

**Comment by SuperAdam47** [comment]
- and add /fe flag arena bow on
- Prevent bowing

**Comment by genboy** [comment]
A Projectiles flag yes, good idea, thank you.

> Hunger flag is new in latest 1.0.7 update
 (coding info markup like this gave me headages and makes me wait for a stable formApi in pmmp)
![minecraft 8_11_2018 11_19_04 pm](https://user-images.githubusercontent.com/30810841/43996214-1c965ca0-9dbe-11e8-83f2-4e08f248815a.png)

**Comment by genboy** [comment]
The shoot flag is added for testing on [master](https://github.com/genboy/Festival)
(whitelisted players and ops can always shoot)
