### ISSUE TITLE
flint & steel protection

### ISSUE THREAD

**Issue by SuperAdam47** [genboy/Festival#75]
No protect for farming and shovel clicking.

![image](https://user-images.githubusercontent.com/16169771/44420880-d2c39080-a587-11e8-8c2b-71c95f9db217.png)

**Comment by SuperAdam47** [comment]
if you touch on no open doors

**Comment by genboy** [comment]
Now testing in development
https://github.com/genboy/Festival/tree/development/
https://poggit.pmmp.io/r/41060/Festival_dev-46.phar

**Comment by SuperAdam47** [comment]
add tnt explode protect
![image](https://user-images.githubusercontent.com/16169771/45320852-77643d00-b54c-11e8-8cca-b8a31a65409a.png)
![image](https://user-images.githubusercontent.com/16169771/45320863-7cc18780-b54c-11e8-8763-c7c6a88dd97b.png)

**Comment by SuperAdam47** [comment]
I don't know.no tested

**Comment by SuperAdam47** [comment]
it's my fault.
