### ISSUE TITLE
Add MobSpawning flag

### ISSUE THREAD

**Issue by iZeaoGamer** [genboy/Festival#78]
So I just came up with a GREAT idea - Add MobSpawning flag, it will disable / enable mob spawning (mobspawners, or spawning them using spawn eggs), depending on what you set it to. If you set the flag to true, then mobs won't spawn, which includes Mob spawners or using spawn eggs. This will be a great addition to this plugin. It would also help prevent mob spawning, whether you're using Spawners, or using eggs - This could also up the security made on this plugin to possibly prevent griefers, or if people are having issues with mob spawning, or can't remove it, then they can simply enable this option to fix that issue. Please take this into consideration, thanks.

**Comment by genboy** [comment]
Hi @iZeaoGamer , yes no mobs flag would be a good addition, i'll check out the possibllites including spawners & eggs.  
I've also tested a barrier for enities a while ago, but then the mobs gather on the barrier, a redirection for the mobs who are heading towards the area would be really cool. Will try to add this soon.

**Comment by iZeaoGamer** [comment]
Okay, thanks.

**Comment by genboy** [comment]
@iZeaoGamer 
I'm testing 2 spawn flags: for mobs and animals. 
Current [master ](https://github.com/genboy/Festival) includes 4.0.0 version bump for testing.

![minecraft 8_26_2018 3_21_55 pm](https://user-images.githubusercontent.com/30810841/44628861-64484f00-a948-11e8-9c2a-6007abf81f74.png)

**Comment by genboy** [comment]
Now testing in development
https://github.com/genboy/Festival/tree/development/
https://poggit.pmmp.io/r/41060/Festival_dev-46.phar

**Comment by genboy** [comment]
Spawning flags work OK now, redirecting entities is bit more complicated and demanding more stidiy. Will be nice future feature.
