### ISSUE TITLE
Suggestion Support BlazinFly plugin

### ISSUE THREAD

**Issue by SuperAdam47** [genboy/Festival#84]
I have a skyblock server. I only authorize VIPs to fly here, but they can't fly because the flight is closed all over the world.

**Comment by genboy** [comment]
What are your configs? Is there a VIP list in BlazinFly? 
Maybe if you set festival world specific configs to allow flight (flight flag false) and in BlazinFly config fill in same world to allow fly?

**Comment by SuperAdam47** [comment]
800 world created for skyblock player island

**Comment by genboy** [comment]
What is this big problem?
@SuperAdam47 Please understand, if questions are not answered properly to track down a problem it takes relatively to much time and then i will not be able to help.

**Comment by SuperAdam47** [comment]
I'm having trouble expressing English 
sorry

**Comment by SuperAdam47** [comment]
I activate the flight with the fly command, but the festival turns off the flight mode.

**Comment by genboy** [comment]
Hi @SuperAdam47,
Is the default configuration flight flag off (false)? To check and maybe reproduce the issue I'd like to check your festival config.yml, can you send it by mail?

**Comment by SuperAdam47** [comment]
flight: true

**Comment by SuperAdam47** [comment]
default

**Comment by genboy** [comment]
To allow flight the flight flag should be false in configs defaults and area's;

Here's an example part of config I think could work for you;
Set default world flight flag to false, or add a specific world after the default with flight flag false:
...

  800 world:
  
    # Keep players from getting hurt? 
    God: false

    # Keep players from getting hurt by other players?
    PVP: false

    # Keep players from flying?
    Flight: false

     # Keep players from editing the world?
    Edit: true

    # Keep players from touching blocks and activating things like chests?
    Touch: false
  
    # Keep players from touching blocks and activating things like chests?
    Effects: false

    # Keep players from seeing enter/leave/description messages?
    Msg: false

    # Prevent players from enter/leaving the area? (barrier)
    Passage: false

    # No explosions allowed in the area?
    Drop: false

    # No explosions allowed in the area?
    TNT: false

    # Keep players from hunger(exhaust) in the area?
    Hunger: false

    # Keep players from executing area event commands without specific perms
    Perms: false


   ..

**Comment by SuperAdam47** [comment]
this is useless

**Comment by SuperAdam47** [comment]
I've tried it many times.

**Comment by genboy** [comment]
If you send me a link to the plugin code that's controlling flight and a copy of your Festival config.yml I may be able to find a solution for your problem - even if it is not Festival related - otherwise this quest is indeed pointless.

**Comment by SuperAdam47** [comment]
# Config file for Festival

# Festival options
Options:
  
  # Messages (tip/pop)  
  Msgtype: pop
  
  # Messages persist display to ops (off/op/on)
  Msgdisplay: off
  
  # Auto whitelist area creator (on/off)
  AutoWhitelist: on

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?  
  God: false

  # Keep players from getting hurt by other players?
  PVP: true

  # Keep players from flying?
  Flight: false

  # Keep players from editing the world?
  Edit: false

  # Keep players from touching blocks and activating things like chests?
  Touch: false
  
  # Keep players from having effects like speed or night vision?
  Effects: false
   
  # Keep players from seeing enter/leave/description messages?
  Msg: true

  # Prevent players from enter/leaving the area? (barrier)
  Passage: false

  # Keep players from dropping items in the area?
  Drop: false

  # No explosions allowed in the area?
  TNT: false

  # Keep players from hunger(exhaust) in the area?
  Hunger: false

  # Keep players from executing area event commands without specific perms
  Perms: false

# Settings for unprotected areas in individual worlds:
Worlds:
 
  Lobby:

    # Keep players from getting hurt? 
    God: true

    # Keep players from getting hurt by other players?
    PVP: false

    # Keep players from flying?
    Flight: true

    # Keep players from editing the world?
    Edit: true

    # Keep players from touching blocks and activating things like chests?
    Touch: false
  
    # Keep players from touching blocks and activating things like chests?
    Effects: false

    # Keep players from seeing enter/leave/description messages?
    Msg: false

    # Prevent players from enter/leaving the area? (barrier)
    Passage: false

    # No explosions allowed in the area?
    Drop: false

    # No explosions allowed in the area?
    TNT: false

    # Keep players from hunger(exhaust) in the area?
    Hunger: false

    # Keep players from executing area event commands without specific perms
    Perms: false

  world:
  
    # Keep players from getting hurt? 
    God: false

    # Keep players from getting hurt by other players?
    PVP: false

    # Keep players from flying?
    Flight: true

    # Keep players from editing the world?
    Edit: true

    # Keep players from touching blocks and activating things like chests?
    Touch: false
  
    # Keep players from touching blocks and activating things like chests?
    Effects: false

    # Keep players from seeing enter/leave/description messages?
    Msg: false

    # Prevent players from enter/leaving the area? (barrier)
    Passage: false

    # Keep players from dropping items in the area?
    Drop: false

    # No explosions allowed in the area?
    TNT: false

    # Keep players from hunger(exhaust) in the area?
    Hunger: false

    # Keep players from executing area event commands without specific perms
    Perms: false

**Comment by genboy** [comment]
OK, in your defaults you have flight: false, but in your sub level default for 'lobby' and 'world' flight: true.
If lobby or world should have flight (by default) then try set flight: false in those worlds. Hope this helps, otherwise i like to look at the other plugin code to see what it does with flight.

**Comment by SuperAdam47** [comment]
what I want is this: 
- I don't want any flights at the lobby.
- In all other worlds, only VIPs can fly.

**Comment by genboy** [comment]
Then all default flight flags should be false except for lobby world - this way festival by default will allow flight everywhere except in lobby -then let another plugin control the player flight with VIP permissions or whatever. 

Festival currently only supports area whitelisting, the configs are not really suitable for world player control, they are default settings to create and manage area's quickly or with automated commands. If the flags are all false festival is not blocking anyrhing and other plugins settings should work

**Comment by SuperAdam47** [comment]
I apologize for tiring you, I understand that this is a problem caused by an plugin.

**Comment by genboy** [comment]
@SuperAdam47 did u get it working the way you like?

**Comment by SuperAdam47** [comment]
no

**Comment by kevinishawesome** [comment]
@genboy, I’m having seriously problem regarding the fly functionality.. if I disable fly, it disables it for everyone, and not even my staff who have op can fly.. but if I enable fly, everyone who visits the server starts flying.. 

I’ve tried installing BlazinFly, but it’s useless.. basically your plugin disables flight everywhere except the areas that I make.. I can just add my staff to whitelist and flight works fine for them there in creative

**Comment by kevinishawesome** [comment]
Maybe you could add a whitelist for unprotected areas?

**Comment by kevinishawesome** [comment]
So what happens when I put fly: false to all 3 configs..

Is that when anyone enters the server (unprotected areas) a message pops up saying “Flying Allowed here” 

Now when I use other plugin /fly to disable fly.. it successfully disables fly but.. your plugin right away pops a message “flying is allowed here” and all of a sudden I start flying again

**Comment by genboy** [comment]
Moved to #89
