### ISSUE TITLE
Can you fix another plugin for the mcpe community ?

### ISSUE THREAD

**Issue by GamerDaniel3000** [genboy/Festival#86]
hey,
can you fix MapImageEngine for Altay (pmmp fork) API: 4.0.0

Please Please Please  :+1:

**Comment by genboy** [comment]
Hi, i like the MapImageEngine very much too. I know it is complicated and not sure when i can find enough time. Might give it a try anyways in next couple of weeks.
Do you have any clue why it's not working or why the creators do not update?

**Comment by genboy** [comment]
see #https://github.com/genboy/pocketmineplugins/issues/35
